"""Interview Copilot 0.1 release schema.

The pre-release development history was squashed before the first Community
release. There is no supported upgrade path from those unpublished schemas.

Revision ID: 0001
Revises:
Create Date: 2026-08-03 13:44:53.664416
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("password_changed_at", sa.DateTime(), nullable=True),
        sa.Column("nickname", sa.String(length=64), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("global_memory_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_dreamed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("active_turn_id", sa.String(), nullable=True),
        sa.Column("subject_type", sa.String(), nullable=True),
        sa.Column("subject_id", sa.String(), nullable=True),
        sa.Column("global_memory_enabled", sa.Boolean(), nullable=True),
        sa.Column("compaction_cursor", sa.Integer(), nullable=True),
        sa.Column("memory_extraction_cursor", sa.Integer(), nullable=True),
        sa.Column("turn_count", sa.Integer(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_type"), "conversations", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    op.create_index(
        "ix_conversations_user_type_arch",
        "conversations",
        ["user_id", "type", "archived_at"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_user_updated",
        "conversations",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "file_assets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("storage_uri", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(), nullable=True),
        sa.Column("upload_status", sa.String(), nullable=False),
        sa.Column("validation_status", sa.String(), nullable=False),
        sa.Column("validation_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_file_assets_object_key"), "file_assets", ["object_key"], unique=True
    )
    op.create_index(
        op.f("ix_file_assets_purpose"), "file_assets", ["purpose"], unique=False
    )
    op.create_index(
        op.f("ix_file_assets_upload_status"),
        "file_assets",
        ["upload_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_file_assets_user_id"), "file_assets", ["user_id"], unique=False
    )
    op.create_index(
        "ix_file_assets_user_purpose",
        "file_assets",
        ["user_id", "purpose"],
        unique=False,
    )
    op.create_table(
        "memory_ability_states",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("skill_type", sa.String(), nullable=False),
        sa.Column("mastery_level", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("evidence_refs_json", sa.Text(), nullable=True),
        sa.Column("search_text", sa.Text(), nullable=True),
        sa.Column("last_evidence_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ability_state_user_mastery",
        "memory_ability_states",
        ["user_id", "mastery_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_ability_states_user_id"),
        "memory_ability_states",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_ability_state_active",
        "memory_ability_states",
        ["user_id", "topic", "skill_type"],
        unique=True,
        postgresql_where=sa.text("archived_at IS NULL"),
        sqlite_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "memory_documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("one_liner", sa.String(), nullable=False),
        sa.Column("last_discussed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "doc_type", name="uq_memory_document_user_type"),
    )
    op.create_index(
        op.f("ix_memory_documents_user_id"),
        "memory_documents",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "outbox_jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(), nullable=False),
        sa.Column("aggregate_type", sa.String(), nullable=True),
        sa.Column("aggregate_id", sa.String(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("locked_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_type", "idempotency_key", name="uq_outbox_jobs_type_idem"
        ),
    )
    op.create_index(
        op.f("ix_outbox_jobs_job_type"), "outbox_jobs", ["job_type"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_jobs_status"), "outbox_jobs", ["status"], unique=False
    )
    op.create_index(
        "ix_outbox_jobs_status_next_run",
        "outbox_jobs",
        ["status", "next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_jobs_user_id"), "outbox_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "user_mcp_servers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("transport", sa.String(length=24), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("args_json", sa.JSON(), nullable=False),
        sa.Column("secrets_ciphertext", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_status", sa.String(length=24), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("tool_count", sa.Integer(), nullable=False),
        sa.Column("checked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_mcp_servers_user_name"),
    )
    op.create_index(
        op.f("ix_user_mcp_servers_user_id"),
        "user_mcp_servers",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_model_credentials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("key_ciphertext", sa.Text(), nullable=False),
        sa.Column("key_masked", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_validated_at", sa.DateTime(), nullable=True),
        sa.Column("last_validation_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_user_model_credentials_user_provider"
        ),
    )
    op.create_index(
        op.f("ix_user_model_credentials_user_id"),
        "user_model_credentials",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_model_provider_settings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("api_base_override", sa.String(), nullable=True),
        sa.Column("organization_id", sa.String(), nullable=True),
        sa.Column("extra_headers_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "provider", name="uq_user_model_provider_settings"
        ),
    )
    op.create_index(
        op.f("ix_user_model_provider_settings_user_id"),
        "user_model_provider_settings",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_model_selections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "role", name="uq_user_model_selections_user_role"
        ),
    )
    op.create_index(
        op.f("ix_user_model_selections_user_id"),
        "user_model_selections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_skills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_skills_user_name"),
    )
    op.create_index(
        op.f("ix_user_skills_user_id"), "user_skills", ["user_id"], unique=False
    )
    op.create_table(
        "agent_checkpoints",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("current_task_id", sa.Integer(), nullable=True),
        sa.Column("next_action", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "conversation_capability_states",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("discovered_skills_json", sa.JSON(), nullable=False),
        sa.Column("permissions_json", sa.JSON(), nullable=False),
        sa.Column("tool_history_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_index(
        op.f("ix_conversation_capability_states_user_id"),
        "conversation_capability_states",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_blocks_json", sa.Text(), nullable=True),
        sa.Column("rewritten_query", sa.Text(), nullable=True),
        sa.Column("tool_call_id", sa.String(), nullable=True),
        sa.Column("tool_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "seq", name="uq_conversation_messages_conversation_seq"
        ),
    )
    op.create_index(
        op.f("ix_conversation_messages_conversation_id"),
        "conversation_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_messages_seq"),
        "conversation_messages",
        ["seq"],
        unique=False,
    )
    op.create_table(
        "conversation_turns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("user_message_seq", sa.Integer(), nullable=True),
        sa.Column("assistant_message_seq", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.String(length=128), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("capability_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("loaded_schemas_json", sa.JSON(), nullable=False),
        sa.Column("budget_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_turns_conversation_id"),
        "conversation_turns",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_turns_heartbeat_at"),
        "conversation_turns",
        ["heartbeat_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_turns_owner_id"),
        "conversation_turns",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_turns_user_id"),
        "conversation_turns",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_asset_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("source_kind", sa.String(), nullable=False),
        sa.Column("source_ref_type", sa.String(), nullable=True),
        sa.Column("source_ref_id", sa.String(), nullable=True),
        sa.Column("source_interview_record_id", sa.String(), nullable=True),
        sa.Column("content_text", sa.Text(), nullable=True),
        sa.Column("storage_uri", sa.String(), nullable=True),
        sa.Column("object_key", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("ref_doc_ids", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_asset_id"],
            ["file_assets.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_knowledge_docs_user_category",
        "knowledge_documents",
        ["user_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_category"),
        "knowledge_documents",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_file_asset_id"),
        "knowledge_documents",
        ["file_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_object_key"),
        "knowledge_documents",
        ["object_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_source_interview_record_id"),
        "knowledge_documents",
        ["source_interview_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_source_kind"),
        "knowledge_documents",
        ["source_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_source_ref_id"),
        "knowledge_documents",
        ["source_ref_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_status"),
        "knowledge_documents",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_user_id"),
        "knowledge_documents",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "memory_audit_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("memory_document_id", sa.String(), nullable=True),
        sa.Column("memory_ability_state_id", sa.String(), nullable=True),
        sa.Column("doc_type", sa.String(), nullable=True),
        sa.Column("topic", sa.String(), nullable=True),
        sa.Column("change_type", sa.String(), nullable=False),
        sa.Column("source_conversation_id", sa.String(), nullable=True),
        sa.Column("source_interview_record_id", sa.String(), nullable=True),
        sa.Column("source_message_range_json", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("before_body", sa.Text(), nullable=True),
        sa.Column("after_body", sa.Text(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_ability_state_id"],
            ["memory_ability_states.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["memory_document_id"], ["memory_documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_audit_logs_user_created",
        "memory_audit_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_audit_logs_user_id"),
        "memory_audit_logs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_memory_audit_logs_idem",
        "memory_audit_logs",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_asset_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("raw_text_snapshot", sa.Text(), nullable=True),
        sa.Column("structured_json", sa.Text(), nullable=True),
        sa.Column("parse_status", sa.String(), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_asset_id"],
            ["file_assets.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_resumes_user_active", "resumes", ["user_id", "archived_at"], unique=False
    )
    op.create_index(op.f("ix_resumes_user_id"), "resumes", ["user_id"], unique=False)
    op.create_index(
        "uq_resumes_one_default_per_user",
        "resumes",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default AND archived_at IS NULL"),
        sqlite_where=sa.text("is_default = 1 AND archived_at IS NULL"),
    )
    op.create_table(
        "session_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("parent_task_id", sa.Integer(), nullable=True),
        sa.Column("owner", sa.String(length=64), nullable=True),
        sa.Column("blocked_by_json", sa.JSON(), nullable=False),
        sa.Column("acceptance_criteria", sa.Text(), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("verification_status", sa.String(length=16), nullable=False),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "task_id", name="uq_session_tasks_session_task"
        ),
    )
    op.create_index(
        op.f("ix_session_tasks_session_id"),
        "session_tasks",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_session_tasks_session_status",
        "session_tasks",
        ["session_id", "status"],
        unique=False,
    )
    op.create_table(
        "agent_tool_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("call_id", sa.String(length=128), nullable=False),
        sa.Column("turn_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("arguments_json", sa.JSON(), nullable=False),
        sa.Column("timeout_seconds", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"], ["conversation_turns.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("turn_id", "call_id", name="uq_agent_tool_calls_turn_call"),
    )
    op.create_index(
        op.f("ix_agent_tool_calls_session_id"),
        "agent_tool_calls",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_tool_calls_turn_id"),
        "agent_tool_calls",
        ["turn_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_tool_calls_user_id"),
        "agent_tool_calls",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=True),
        sa.Column("node_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.String(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("index_status", sa.String(), nullable=False),
        sa.Column("lexical_index_id", sa.String(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["knowledge_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_chunks_doc_order",
        "document_chunks",
        ["document_id", "chunk_index"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"),
        "document_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunks_node_id"), "document_chunks", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_user_id"), "document_chunks", ["user_id"], unique=False
    )
    op.create_index(
        "ix_document_chunks_user_source",
        "document_chunks",
        ["user_id", "source_kind"],
        unique=False,
    )
    op.create_table(
        "interview_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("tag", sa.String(length=32), nullable=True),
        sa.Column("audio_file_asset_id", sa.String(), nullable=True),
        sa.Column("resume_file_asset_id", sa.String(), nullable=True),
        sa.Column("jd_file_asset_id", sa.String(), nullable=True),
        sa.Column("resume_id", sa.String(), nullable=True),
        sa.Column("resume_source", sa.String(), nullable=True),
        sa.Column("resume_title_snapshot", sa.String(), nullable=True),
        sa.Column("resume_text_snapshot", sa.Text(), nullable=True),
        sa.Column("jd_text_snapshot", sa.Text(), nullable=True),
        sa.Column("resume_structured_snapshot_json", sa.Text(), nullable=True),
        sa.Column("jd_structured_json", sa.Text(), nullable=True),
        sa.Column("transcript_id", sa.String(), nullable=True),
        sa.Column("interview_plan", sa.Text(), nullable=True),
        sa.Column("analysis_json", sa.Text(), nullable=True),
        sa.Column("analysis_schema_version", sa.Integer(), nullable=False),
        sa.Column("debrief_summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("analyzed_qa_count", sa.Integer(), nullable=False),
        sa.Column("celery_task_id", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_dreamed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_records_status"),
        "interview_records",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_records_transcript_id"),
        "interview_records",
        ["transcript_id"],
        unique=False,
    )
    op.create_index(
        "ix_interview_records_user_created",
        "interview_records",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_records_user_id"),
        "interview_records",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_interview_records_user_last_dreamed",
        "interview_records",
        ["user_id", "last_dreamed_at"],
        unique=False,
    )
    op.create_table(
        "resume_sections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("resume_id", sa.String(), nullable=False),
        sa.Column("section_type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("order_idx", sa.Integer(), nullable=False),
        sa.Column("embedding_status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_sections_resume_id"),
        "resume_sections",
        ["resume_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_sections_section_type"),
        "resume_sections",
        ["section_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resume_sections_user_id"), "resume_sections", ["user_id"], unique=False
    )
    op.create_table(
        "interview_qa",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("order_idx", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("phase_label", sa.String(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("question_summary", sa.String(), nullable=True),
        sa.Column("is_follow_up", sa.Boolean(), nullable=False),
        sa.Column("parent_qa_id", sa.String(), nullable=True),
        sa.Column("grounding_refs_json", sa.Text(), nullable=True),
        sa.Column("follow_up_depth", sa.Integer(), nullable=False),
        sa.Column("source_segment_start", sa.Float(), nullable=True),
        sa.Column("source_segment_end", sa.Float(), nullable=True),
        sa.Column("question_audio_url", sa.String(), nullable=True),
        sa.Column("answer_audio_url", sa.String(), nullable=True),
        sa.Column("answer_audio_file_asset_id", sa.String(), nullable=True),
        sa.Column("answer_input_mode", sa.String(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=True),
        sa.Column("topic", sa.String(length=80), nullable=True),
        sa.Column("answer_quality_json", sa.JSON(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("critique", sa.Text(), nullable=True),
        sa.Column("improved_answer", sa.Text(), nullable=True),
        sa.Column("key_points_json", sa.Text(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.Column("saved_document_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_qa_id"],
            ["interview_qa.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"], ["interview_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_qa_record_id"), "interview_qa", ["record_id"], unique=False
    )
    op.create_index(
        "ix_interview_qa_record_order",
        "interview_qa",
        ["record_id", "order_idx"],
        unique=False,
    )
    op.create_table(
        "interview_transcripts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("segments_json", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"], ["interview_records.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_transcripts_record_id"),
        "interview_transcripts",
        ["record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_transcripts_user_id"),
        "interview_transcripts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "mock_interview_runtime",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("interview_record_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_stage_key", sa.String(), nullable=True),
        sa.Column("stage_index", sa.Integer(), nullable=False),
        sa.Column("current_question_text", sa.Text(), nullable=True),
        sa.Column("current_question_message_id", sa.Integer(), nullable=True),
        sa.Column("plan_json", sa.Text(), nullable=True),
        sa.Column("plan_template_key", sa.String(), nullable=False),
        sa.Column("interviewer_style", sa.String(), nullable=False),
        sa.Column("voice_mode", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["interview_record_id"], ["interview_records.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mock_interview_runtime_interview_record_id"),
        "mock_interview_runtime",
        ["interview_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mock_interview_runtime_status"),
        "mock_interview_runtime",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mock_interview_runtime_user_id"),
        "mock_interview_runtime",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_mock_runtime_user_status",
        "mock_interview_runtime",
        ["user_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mock_runtime_user_status", table_name="mock_interview_runtime")
    op.drop_index(
        op.f("ix_mock_interview_runtime_user_id"), table_name="mock_interview_runtime"
    )
    op.drop_index(
        op.f("ix_mock_interview_runtime_status"), table_name="mock_interview_runtime"
    )
    op.drop_index(
        op.f("ix_mock_interview_runtime_interview_record_id"),
        table_name="mock_interview_runtime",
    )
    op.drop_table("mock_interview_runtime")
    op.drop_index(
        op.f("ix_interview_transcripts_user_id"), table_name="interview_transcripts"
    )
    op.drop_index(
        op.f("ix_interview_transcripts_record_id"), table_name="interview_transcripts"
    )
    op.drop_table("interview_transcripts")
    op.drop_index("ix_interview_qa_record_order", table_name="interview_qa")
    op.drop_index(op.f("ix_interview_qa_record_id"), table_name="interview_qa")
    op.drop_table("interview_qa")
    op.drop_index(op.f("ix_resume_sections_user_id"), table_name="resume_sections")
    op.drop_index(op.f("ix_resume_sections_section_type"), table_name="resume_sections")
    op.drop_index(op.f("ix_resume_sections_resume_id"), table_name="resume_sections")
    op.drop_table("resume_sections")
    op.drop_index(
        "ix_interview_records_user_last_dreamed", table_name="interview_records"
    )
    op.drop_index(op.f("ix_interview_records_user_id"), table_name="interview_records")
    op.drop_index("ix_interview_records_user_created", table_name="interview_records")
    op.drop_index(
        op.f("ix_interview_records_transcript_id"), table_name="interview_records"
    )
    op.drop_index(op.f("ix_interview_records_status"), table_name="interview_records")
    op.drop_table("interview_records")
    op.drop_index("ix_document_chunks_user_source", table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_user_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_node_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index("ix_document_chunks_doc_order", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_agent_tool_calls_user_id"), table_name="agent_tool_calls")
    op.drop_index(op.f("ix_agent_tool_calls_turn_id"), table_name="agent_tool_calls")
    op.drop_index(op.f("ix_agent_tool_calls_session_id"), table_name="agent_tool_calls")
    op.drop_table("agent_tool_calls")
    op.drop_index("ix_session_tasks_session_status", table_name="session_tasks")
    op.drop_index(op.f("ix_session_tasks_session_id"), table_name="session_tasks")
    op.drop_table("session_tasks")
    op.drop_index(
        "uq_resumes_one_default_per_user",
        table_name="resumes",
        postgresql_where=sa.text("is_default AND archived_at IS NULL"),
        sqlite_where=sa.text("is_default = 1 AND archived_at IS NULL"),
    )
    op.drop_index(op.f("ix_resumes_user_id"), table_name="resumes")
    op.drop_index("ix_resumes_user_active", table_name="resumes")
    op.drop_table("resumes")
    op.drop_index("uq_memory_audit_logs_idem", table_name="memory_audit_logs")
    op.drop_index(op.f("ix_memory_audit_logs_user_id"), table_name="memory_audit_logs")
    op.drop_index("ix_memory_audit_logs_user_created", table_name="memory_audit_logs")
    op.drop_table("memory_audit_logs")
    op.drop_index(
        op.f("ix_knowledge_documents_user_id"), table_name="knowledge_documents"
    )
    op.drop_index(
        op.f("ix_knowledge_documents_status"), table_name="knowledge_documents"
    )
    op.drop_index(
        op.f("ix_knowledge_documents_source_ref_id"), table_name="knowledge_documents"
    )
    op.drop_index(
        op.f("ix_knowledge_documents_source_kind"), table_name="knowledge_documents"
    )
    op.drop_index(
        op.f("ix_knowledge_documents_source_interview_record_id"),
        table_name="knowledge_documents",
    )
    op.drop_index(
        op.f("ix_knowledge_documents_object_key"), table_name="knowledge_documents"
    )
    op.drop_index(
        op.f("ix_knowledge_documents_file_asset_id"), table_name="knowledge_documents"
    )
    op.drop_index(
        op.f("ix_knowledge_documents_category"), table_name="knowledge_documents"
    )
    op.drop_index("ix_knowledge_docs_user_category", table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index(
        op.f("ix_conversation_turns_user_id"), table_name="conversation_turns"
    )
    op.drop_index(
        op.f("ix_conversation_turns_owner_id"), table_name="conversation_turns"
    )
    op.drop_index(
        op.f("ix_conversation_turns_heartbeat_at"), table_name="conversation_turns"
    )
    op.drop_index(
        op.f("ix_conversation_turns_conversation_id"), table_name="conversation_turns"
    )
    op.drop_table("conversation_turns")
    op.drop_index(
        op.f("ix_conversation_messages_seq"), table_name="conversation_messages"
    )
    op.drop_index(
        op.f("ix_conversation_messages_conversation_id"),
        table_name="conversation_messages",
    )
    op.drop_table("conversation_messages")
    op.drop_index(
        op.f("ix_conversation_capability_states_user_id"),
        table_name="conversation_capability_states",
    )
    op.drop_table("conversation_capability_states")
    op.drop_table("agent_checkpoints")
    op.drop_index(op.f("ix_user_skills_user_id"), table_name="user_skills")
    op.drop_table("user_skills")
    op.drop_index(
        op.f("ix_user_model_selections_user_id"), table_name="user_model_selections"
    )
    op.drop_table("user_model_selections")
    op.drop_index(
        op.f("ix_user_model_provider_settings_user_id"),
        table_name="user_model_provider_settings",
    )
    op.drop_table("user_model_provider_settings")
    op.drop_index(
        op.f("ix_user_model_credentials_user_id"), table_name="user_model_credentials"
    )
    op.drop_table("user_model_credentials")
    op.drop_index(op.f("ix_user_mcp_servers_user_id"), table_name="user_mcp_servers")
    op.drop_table("user_mcp_servers")
    op.drop_index(op.f("ix_outbox_jobs_user_id"), table_name="outbox_jobs")
    op.drop_index("ix_outbox_jobs_status_next_run", table_name="outbox_jobs")
    op.drop_index(op.f("ix_outbox_jobs_status"), table_name="outbox_jobs")
    op.drop_index(op.f("ix_outbox_jobs_job_type"), table_name="outbox_jobs")
    op.drop_table("outbox_jobs")
    op.drop_index(op.f("ix_memory_documents_user_id"), table_name="memory_documents")
    op.drop_table("memory_documents")
    op.drop_index(
        "uq_ability_state_active",
        table_name="memory_ability_states",
        postgresql_where=sa.text("archived_at IS NULL"),
        sqlite_where=sa.text("archived_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_memory_ability_states_user_id"), table_name="memory_ability_states"
    )
    op.drop_index("ix_ability_state_user_mastery", table_name="memory_ability_states")
    op.drop_table("memory_ability_states")
    op.drop_index("ix_file_assets_user_purpose", table_name="file_assets")
    op.drop_index(op.f("ix_file_assets_user_id"), table_name="file_assets")
    op.drop_index(op.f("ix_file_assets_upload_status"), table_name="file_assets")
    op.drop_index(op.f("ix_file_assets_purpose"), table_name="file_assets")
    op.drop_index(op.f("ix_file_assets_object_key"), table_name="file_assets")
    op.drop_table("file_assets")
    op.drop_index("ix_conversations_user_updated", table_name="conversations")
    op.drop_index("ix_conversations_user_type_arch", table_name="conversations")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_type"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
