// Interaction prototype. Only URL parsing invokes a real service; recommendation is explicitly simulated.
(()=>{
 const oldRender=render,oldResults=results,oldCompany=companyDetail,oldReview=review;
 const state={open:false,scope:null,messages:[],task:null,result:null,draft:'',useProfile:false,token:0,controller:null};
 const panel=document.createElement('aside');panel.id='market-collaboration';panel.setAttribute('aria-label','岗位市场协作');document.body.append(panel);
 const selectedCompanies=()=>state.scope?.type==='companies'?state.scope.items:state.scope?.type==='company'?[state.scope.item]:[];
 const label=()=>selectedCompanies().length?selectedCompanies().map(c=>c.name).join('、'):state.scope?.type==='job'?state.scope.item.company+' · '+state.scope.item.title:'整个岗位市场';
 function markSelection(){document.querySelectorAll('[data-co-select-company]').forEach(b=>{const selected=selectedCompanies().some(c=>c.name===b.dataset.coSelectCompany);b.classList.toggle('is-selected',selected);b.setAttribute('aria-pressed',String(selected));b.title=(selected?'移出协作':'加入协作')+' · '+b.dataset.coSelectCompany;b.setAttribute('aria-label',b.title)})}
 function toggleCompany(name){const item=companies.find(c=>c.name===name);if(!item)return;const items=selectedCompanies().slice(),index=items.findIndex(c=>c.name===name);if(index<0)items.push(item);else items.splice(index,1);stop();state.scope=items.length?{type:'companies',items}:null;state.result=null;state.task=null;state.open=true;message('system',items.length?'协作范围已更新：'+items.map(c=>c.name).join('、')+'。':'已取消公司选择，恢复整个岗位市场范围。');modal.close();redrawResults();persist()}
 function persist(){try{sessionStorage.setItem('career-market-collaboration-v1',JSON.stringify({scope:state.scope,messages:state.messages.slice(-20),draft:state.draft,useProfile:state.useProfile,task:state.task,result:state.result}))}catch{}}
 try{const saved=JSON.parse(sessionStorage.getItem('career-market-collaboration-v1')||'null');if(saved){state.scope=saved.scope;state.messages=saved.messages||[];state.draft=saved.draft||'';state.useProfile=!!saved.useProfile;state.task=saved.task||null;state.result=saved.result||null;if(state.task?.status==='running'){state.task.status='stopped';state.task.progress='页面已刷新，可重试继续本次任务。'}}}catch{}
 function busy(){return state.task?.status==='running'}
 function stop(){state.token++;state.controller?.abort();state.controller=null;if(busy()){state.task.status='stopped';state.messages.push({role:'system',text:'任务已停止。可以修改条件后重新开始。'})}}
 function message(role,text){state.messages.push({role,text});persist()}
 function entry(){return `<section class="agent-entry"><svg class="hero-pattern" viewBox="0 0 1200 240" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="ribbon" x2="1" y2="1"><stop stop-color="#8fc7ff" stop-opacity=".26"/><stop offset="1" stop-color="#c7d7ff" stop-opacity=".04"/></linearGradient></defs><path d="M-80 210 C40 95 225 -28 164 78 C120 156 -15 210 -45 271 C10 245 260 94 190 174 C115 259 -30 303 -80 300 Z" fill="url(#ribbon)"/><path d="M940 -40 C860 42 980 115 1065 51 C1120 9 1250 -37 1240 25 C1230 90 1070 139 1050 178 C1030 225 1225 128 1270 94 L1290 280 C1110 320 961 271 1070 188 C1200 95 1320 22 1210 -28 C1110 -80 1000 66 960 39 C944 26 970 -8 1005 -40 Z" fill="url(#ribbon)"/></svg><div class="entry-caption"><div><strong>这次想找什么机会？</strong><small>说说你的方向，或粘贴官网岗位链接，一起找到下一站。</small></div></div><form id="market-agent-form"><span class="prompt-spark" aria-hidden="true">✧</span><input name="prompt" aria-label="岗位市场任务" placeholder="帮我看看腾讯的技术岗位，或粘贴具体岗位链接…" value="${esc(state.draft)}" required><button type="submit" class="primary" aria-label="开始协作">➤</button></form><div class="agent-suggestions"><button data-co="companies"><span aria-hidden="true">▥</span> 找公司</button><button data-co="jobs"><span aria-hidden="true">⌕</span> 找具体岗位</button><button data-co="link-help"><span aria-hidden="true">↗</span> 解析岗位链接</button><button data-co="resume"><span aria-hidden="true">◷</span> 继续上次协作</button></div><div class="hero-note" aria-hidden="true"><svg class="note-arrow" viewBox="0 0 65 40" fill="none"><path d="M3 33Q23 9 55 10M48 5l9 5-7 6" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg><div class="note-cn">更好的职业机会<br>从这里开始</div><div class="note-en">AI for a<br>Better Career <span>✧</span></div></div></section>`}
 function paint(){markSelection();const visible=state.open&&view==='market';document.body.classList.toggle('co-open',visible);panel.hidden=!visible;if(!visible)return;
 const task=state.task;panel.innerHTML=`<header class="co-header"><div><span class="co-spark">✧</span><strong>一起找机会</strong></div><button data-co="collapse" aria-label="收起协作栏">⇥</button></header><div class="co-scope"><small>当前协作对象</small><div><b>${selectedCompanies().length?'已选 '+selectedCompanies().length+' 家公司':esc(label())}</b>${state.scope?'<button data-co="clear-scope" aria-label="清除协作对象">×</button>':''}</div>${selectedCompanies().length?`<div class="co-company-chips">${selectedCompanies().map(c=>`<button data-co-select-company="${esc(c.name)}" aria-label="移出协作 · ${esc(c.name)}">${esc(c.name)} <span aria-hidden="true">×</span></button>`).join('')}</div>`:''}<label><input type="checkbox" id="co-profile" ${state.useProfile?'checked':''}> 使用我的个人资料</label><button data-co="scope-info" class="scope-info">查看范围</button></div><div class="co-transcript" role="log" aria-live="polite">${state.messages.length?state.messages.map(m=>`<div class="co-message ${m.role}">${esc(m.text)}</div>`).join(''):`<div class="co-welcome"><span>✧</span><h3>从一个方向开始</h3><p>你可以找公司、查看具体岗位，或围绕选中的机会继续讨论。</p><div class="co-examples"><button data-co="companies">看看候选公司</button><button data-co="jobs">看看具体岗位</button></div></div>`}${task?`<div class="co-task ${task.status}"><div class="row"><strong>${task.kind==='parse'?'读取官网岗位':'交互演示'}</strong><small>${{running:'进行中',done:'已完成',error:'未完成',stopped:'已停止'}[task.status]}</small></div><p>${esc(task.progress||'')}</p>${busy()?'<button data-co="stop">停止</button>':''}${task.status==='error'||task.status==='stopped'?'<button data-co="retry">重试本次任务</button>':''}${state.result?'<button data-co="show-results">在列表查看结果 →</button>':''}</div>`:''}</div><footer class="co-footer"><div class="co-quick"><button data-co="conditions">调整条件</button><button data-co="new">新协作</button></div><form id="co-followup-form"><textarea name="prompt" rows="2" aria-label="继续协作" placeholder="补充条件，或粘贴岗位链接…" required>${esc(state.draft)}</textarea><button class="primary" type="submit" ${busy()?'disabled':''}>发送 ↑</button></form><small>演示分析不调用模型，不代表真实匹配结论。</small></footer>`;
 const log=panel.querySelector('.co-transcript');log.scrollTop=log.scrollHeight;
 }
 render=function(){document.body.classList.toggle('market-view',view==='market');oldRender();if(view==='market'){app.querySelector('.dock')?.remove();app.querySelector('.top').insertAdjacentHTML('afterend',entry())}paint()};
 function applyFilters(items,kind){const f=state.task?.filters||{};return items.filter(c=>{const text=kind==='companies'?[c.name,c.roles,c.industry].join(' '):[c.company,c.title,c.category,...c.sections.map(s=>s.text)].join(' ');return (!f.keyword||text.toLowerCase().includes(f.keyword.toLowerCase()))&&(kind!=='companies'||!f.city||c.cities.includes(f.city))})}
 results=function(){const filters=document.querySelector('.filters');if(filters)filters.hidden=!!state.result?.shown;if(!state.result?.shown){oldResults();return}const r=state.result,items=r.items;document.querySelector('#results').innerHTML=`<div class="co-results-head"><div><strong>${r.kind==='companies'?'候选公司':'具体岗位'}</strong><small>${r.real?'官网解析结果':'交互演示 · 当前预览资料'} · ${items.length} 项</small></div><button data-co="return-directory">返回原目录</button></div>${items.length?items.map((c,i)=>r.kind==='companies'?`<article class="co-result-row"><div><small>${String(i+1).padStart(2,'0')}</small><h3>${esc(c.name)}</h3><p>${esc(c.roles)}</p><small>${esc(c.cities)}</small></div><div><button data-company="${esc(c.name)}">公司详情</button><button data-co-select-company="${esc(c.name)}">继续讨论</button></div></article>`:`<article class="co-result-row"><div><h3>${esc(c.title)}</h3><p>${esc(c.company)} · ${esc(c.audience||'招聘类型未填写')}</p><small>${r.real?'刚刚从官网读取':'来自已收集 JD'}</small></div><div><button data-co-result="${i}">查看岗位</button><button data-co-discuss-job="${i}">继续讨论</button></div></article>`).join(''):`<div class="empty"><h3>当前范围内没有符合条件的结果</h3><p>可以放宽条件，或返回目录继续浏览。</p><button data-co="conditions">调整条件</button></div>`}`};
 document.addEventListener('click',e=>{if(e.target.closest('[data-tab]')&&state.result){state.result.shown=false;persist()}},true);
 function redrawResults(){if(view==='market'){results();paint()}}
 function scope(type,item){stop();state.scope=type?{type,item}:null;state.result=null;state.task=null;state.messages=[];state.draft='';state.open=true;message('system','已切换到“'+label()+'”。新的协作不会携带上一对象的对话。');modal.close();redrawResults();persist()}
 companyDetail=function(name){oldCompany(name);document.querySelector('#modalbody .actions')?.insertAdjacentHTML('beforeend',`<button data-co-select-company="${esc(name)}">✧ 让 Agent 帮我看看</button>`)};
 review=function(){oldReview();const footer=document.querySelector('#modalbody .detail-footer');footer?.insertAdjacentHTML('afterbegin','<button data-co-select-current-job>✧ 讨论这个岗位</button>');if(footer&&!collected().some(j=>j.url===S.url)){const b=document.createElement('button');b.textContent='收集岗位';b.onclick=()=>{keepJob(structuredClone(S));b.textContent='已收集';b.disabled=true;toast('岗位已收集')};footer.prepend(b)}};
 function inferKind(text){return /https?:\/\//i.test(text)?'parse':/岗位|职位|JD|jd/.test(text)?'jobs':'companies'}
 async function run(text,kind=inferKind(text),filters=null,simulateFailure=false){stop();const token=++state.token;state.open=true;state.draft='';state.result=null;state.task={text,kind,filters:filters||{},status:'running',progress:kind==='parse'?'正在打开官网并等待岗位内容…':'正在准备演示结果…'};message('user',text);render();
  try{let items;if(simulateFailure){await new Promise(r=>setTimeout(r,400));throw Error('这是一次模拟读取失败，用于检查重试交互；没有访问外部服务。')}
   if(kind==='parse'){const match=text.match(/https?:\/\/[^\s<>]+/i);if(!match)throw Error('请粘贴具体岗位详情链接。');const url=validLink(match[0]);state.controller=new AbortController();const res=await fetch('/api/jobs/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url}),signal:state.controller.signal});const j=await res.json();if(!res.ok)throw Error(j.error||'读取失败');items=[j]}
   else{await new Promise(r=>setTimeout(r,550));if(token!==state.token)return;state.task.progress='已限定协作范围，正在整理可查看的结果…';paint();await new Promise(r=>setTimeout(r,550));if(kind==='companies')items=selectedCompanies().length?selectedCompanies().slice():state.scope?.type==='job'?companies.filter(c=>c.name===state.scope.item.company):companies.slice();else items=state.scope?.type==='job'?[state.scope.item]:collected().filter(j=>!selectedCompanies().length||selectedCompanies().some(c=>c.name===j.company));items=applyFilters(items,kind)}
   if(token!==state.token)return;state.result={kind:kind==='companies'?'companies':'jobs',items,real:kind==='parse',shown:true};state.task.status='done';state.task.progress=kind==='parse'?'已读取岗位正文，请核对后收集或创建工作台。':`已展示 ${items.length} 项。结果仅来自现有预览资料，不含真实 AI 排名。`;message('assistant',kind==='parse'?'已读取“'+items[0].company+' · '+items[0].title+'”。查看岗位后可以保存或创建工作台。':kind==='jobs'?'左侧是当前范围内已有 JD 的岗位。真实的官网检索与匹配尚未接入，本次展示的是交互效果。':'左侧展示当前目录中的候选公司。你可以调整明确的筛选条件，或多选公司继续比较。');redrawResults();
  }catch(e){if(token!==state.token||e.name==='AbortError')return;state.task.status='error';state.task.progress=e.message;message('system',e.message);redrawResults()}finally{if(token===state.token){state.controller=null;persist()}}
 }
 function conditions(){const f=state.task?.filters||{};show('调整本次协作条件',`<form id="co-conditions-form"><label>关键词<input name="keyword" value="${esc(f.keyword||'')}" placeholder="例如：技术、腾讯、数据库"></label><label>地点摘要包含（公司结果）<input name="city" value="${esc(f.city||'')}" placeholder="例如：北京"></label><p class="helper muted">此处真实筛选预览数据；自由对话的语义理解将在 Agent 接入后提供。</p><button type="submit" class="primary">应用并更新结果</button></form>`)}
 function resultJob(i){const j=state.result?.items[i];if(!j)return;S=j;review()}
 document.addEventListener('input',e=>{if(e.target.closest('#market-agent-form,#co-followup-form')){state.draft=e.target.value;persist()}});
 document.addEventListener('change',e=>{if(e.target.id==='co-profile'){state.useProfile=e.target.checked;persist()}});
 document.addEventListener('submit',e=>{const id=e.target.id;if(!['market-agent-form','co-followup-form','co-conditions-form'].includes(id))return;e.preventDefault();e.stopImmediatePropagation();if(id==='co-conditions-form'){const d=new FormData(e.target),f={keyword:String(d.get('keyword')).trim(),city:String(d.get('city')).trim()};modal.close();run('按新条件更新结果',state.task?.kind==='companies'?'companies':'jobs',f);return}const text=new FormData(e.target).get('prompt').trim();if(text)run(text)},true);
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const action=b.dataset.co;const has=action||b.hasAttribute('data-co-select-company')||b.hasAttribute('data-co-select-current-job')||b.hasAttribute('data-co-result')||b.hasAttribute('data-co-discuss-job');if(!has)return;e.preventDefault();e.stopImmediatePropagation();
  if(b.hasAttribute('data-co-select-company')){toggleCompany(b.dataset.coSelectCompany);return}
  if(b.hasAttribute('data-co-select-current-job')){scope('job',structuredClone(S));return}
  if(b.hasAttribute('data-co-discuss-job')){scope('job',structuredClone(state.result.items[+b.dataset.coDiscussJob]));return}
  if(b.hasAttribute('data-co-result')){resultJob(+b.dataset.coResult);return}
  switch(action){case'resume':state.open=true;paint();break;case'collapse':state.open=false;render();break;case'companies':run('看看当前范围内的候选公司','companies');break;case'jobs':run('查看当前范围内的具体岗位','jobs');break;case'link-help':state.open=true;message('assistant','把在官网选中的岗位详情链接发到这里。我会读取实际页面，结果将在左侧展示。');render();panel.querySelector('textarea').focus();break;case'clear-scope':scope(null,null);break;case'stop':stop();paint();break;case'retry':if(state.task)run(state.task.text,state.task.kind,state.task.filters);break;case'show-results':if(state.result)state.result.shown=true;redrawResults();break;case'return-directory':if(state.result)state.result.shown=false;redrawResults();break;case'conditions':conditions();break;case'failure-demo':run('演示一次读取异常',state.task?.kind==='parse'?'jobs':state.task?.kind||'companies',state.task?.filters,true);break;case'new':stop();state.task=null;state.result=null;state.messages=[];state.draft='';persist();render();break;case'scope-info':show('本次协作范围',`<dl class="facts"><dt>当前对象</dt><dd>${esc(label())}</dd><dt>岗位资料</dt><dd>${state.scope?.type==='job'?'仅此岗位的 JD 与来源链接':selectedCompanies().length?'所选公司目录及这些公司已收集的岗位':'当前招聘目录与已收集岗位'}</dd><dt>个人资料</dt><dd>${state.useProfile?'已选择纳入；本轮演示未读取或发送个人档案':'未选择，不纳入'}</dd></dl><p class="muted">推荐和分析是交互演示，不会把资料发送给模型。切换对象会开始新的协作。</p>`);break}
 });
 // Keep selection actions available in the directory and saved-job list, including after filters change.
 const resultObserver=new MutationObserver(()=>{markSelection();const container=document.querySelector('#results');if(!container||state.result?.shown)return;container.querySelectorAll('[data-job]').forEach(b=>{if(b.parentElement.querySelector('.row-collaborate'))return;const co=document.createElement('button');co.className='row-collaborate';co.textContent='✧';co.setAttribute('aria-label','围绕此项协作');co.onclick=()=>{if(b.dataset.company)scope('company',companies.find(c=>c.name===b.dataset.company));else scope('job',collected().find(j=>j.url===b.dataset.job))};b.after(co)})});resultObserver.observe(app,{subtree:true,childList:true});
 render();
})();
