// Focused dialog navigation, job capture, and evidence-backed application progress.
let parsedMetadata=null;let screens=[],parseController=null,draft={company:'',title:'',url:'',jd:''},mode='link';
function rememberScreen(){return {html:document.querySelector('#modalbody').innerHTML,values:[...document.querySelectorAll('#modalbody input,#modalbody textarea')].map(e=>[e.name,e.value])}}
show=function(title,body){if(modal.open)screens.push(rememberScreen());else screens=[];document.querySelector('#modalbody').innerHTML=`<div class="dialog-heading">${screens.length?'<button data-flow="back" aria-label="返回上一级">← 返回</button>':''}<h2>${esc(title)}</h2></div>${body}`;if(!modal.open)modal.showModal();document.querySelector('#modalbody').scrollTop=0};
function cancelParse(){parseController?.abort();parseController=null}
function backScreen(){cancelParse();const prev=screens.pop();if(!prev){modal.close();return}document.querySelector('#modalbody').innerHTML=prev.html;prev.values.forEach(([name,value])=>{const el=[...document.querySelectorAll('#modalbody input,#modalbody textarea')].find(x=>x.name===name);if(el)el.value=value});mode=document.querySelector('.capture-tabs .chosen')?.dataset.mode||mode;const pb=document.querySelector('[data-flow="parse"]');if(pb){pb.disabled=false;pb.textContent='解析岗位'}document.querySelector('#modalbody').scrollTop=0}
modal.addEventListener('close',()=>{screens=[];cancelParse()});
function formBody(){return `<div class="capture-tabs"><button type="button" data-mode="link" class="${mode==='link'?'chosen':''}">↗ 链接解析</button><button type="button" data-mode="manual" class="${mode==='manual'?'chosen':''}">✎ 手动填写</button></div><form id="capture-form"><label>岗位详情链接<input type="url" name="url" required value="${esc(draft.url)}" placeholder="粘贴在官网选中的具体岗位链接"></label>${mode==='link'?`<p class="muted helper">解析公司、岗位名称和 JD，核对后再保存。</p><button type="button" class="primary" data-flow="parse">解析岗位</button><p class="helper muted">部分需要登录或动态加载的网站暂时无法自动读取，可切换手动填写。</p>`:`<div class="form-grid"><label>公司<input name="company" required maxlength="100" value="${esc(draft.company)}"></label><label>岗位名称<input name="title" required maxlength="180" value="${esc(draft.title)}"></label></div><label>职位描述与要求<textarea name="jd" required minlength="20" maxlength="60000" placeholder="填写职责、要求和其他岗位信息">${esc(draft.jd)}</textarea></label><button type="submit" class="primary">保存岗位</button>`}<p id="capture-error" role="status"></p></form>`}
function rememberDraft(){document.querySelectorAll('#capture-form [name]').forEach(e=>draft[e.name]=e.value)}
addJob=function(company=''){parsedMetadata=null;draft={company,title:'',url:'',jd:''};mode='link';show('添加岗位',formBody())};
function switchMode(m){rememberDraft();cancelParse();mode=m;const heading=document.querySelector('.dialog-heading').outerHTML;document.querySelector('#modalbody').innerHTML=heading+formBody()}
function validLink(value){const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error('请填写有效的网页链接');return u.href}
function keepJob(j){const items=collected().filter(x=>x.url!==j.url);items.push(j);localStorage.setItem('career-collected-jobs-v1',JSON.stringify(items));S=j}
async function parseLink(){rememberDraft();const error=document.querySelector('#capture-error'),button=document.querySelector('[data-flow="parse"]');try{validLink(draft.url)}catch(e){error.textContent=e.message;return}cancelParse();const controller=new AbortController();parseController=controller;button.disabled=true;button.textContent='正在读取官网…';error.textContent='';try{const response=await fetch('/api/jobs/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:draft.url}),signal:controller.signal});const j=await response.json();if(!response.ok)throw Error(j.error||'未能读取岗位');if(controller.signal.aborted)return;parsedMetadata=j;draft={company:j.company,title:j.title,url:j.url,jd:j.sections.map(x=>x.title+'\n'+x.text).join('\n\n')};show('核对解析结果',`<form id="parsed-form"><label>公司<input name="company" required value="${esc(draft.company)}"></label><label>岗位名称<input name="title" required value="${esc(draft.title)}"></label><label>职位描述与要求<textarea name="jd" required minlength="20">${esc(draft.jd)}</textarea></label><small>来源：${esc(j.url)}</small><div class="detail-footer"><span>确认内容后保存到已收集岗位</span><button type="submit" class="primary">确认保存</button></div></form>`)}catch(e){if(e.name!=='AbortError')error.textContent=e.message}finally{button.disabled=false;button.textContent='解析岗位';if(parseController===controller)parseController=null}}
function nodes(w){return w.nodes?.length?w.nodes:[{id:'preparation',name:'准备投递',time:w.createdAt,origin:'用户创建工作台',url:'',reference:w.source.url}]}
function nodeStrip(w){return `<div class="node-strip">${nodes(w).map((n,i)=>`<button data-node="${esc(n.id)}" data-owner="${w.id}" class="${i===nodes(w).length-1?'latest':''}" title="查看节点与来源"><span class="node-dot"></span>${esc(n.name)}<small>${n.url?'↗':'ⓘ'}</small></button>`).join('<span class="node-line"></span>')}</div>`}
function applicationLink(w){try{return JSON.parse(localStorage.getItem('career-company-applications-v1')||'{}')[w.source.company]||''}catch{return ''}}
applications=function(){const items=load();app.innerHTML=`<div class="top"><div><h1>我的投递</h1><p class="muted">${items.length} 个岗位，记录每一步进展。</p></div><button data-view="market">发现机会 →</button></div><div class="application-list">${items.map(w=>`<article class="application-card"><div class="row"><div class="identity"><div class="company-mark">${esc(w.source.company.slice(0,2))}</div><div><p class="company-name">${esc(w.source.company)}</p><h2>${esc(w.source.title)}</h2><small>${esc([w.source.audience,w.source.category].filter(Boolean).join(' · '))}</small></div></div><button data-workspace="${w.id}" class="workspace-entry">进入工作台　→</button></div><div class="application-bottom">${nodeStrip(w)}<small>${new Date(nodes(w).at(-1).time).toLocaleDateString('zh-CN')} 更新</small></div></article>`).join('')||'<div class="panel empty">还没有岗位，选中具体岗位后即可开始准备。</div>'}</div>`};
workspace=function(){const w=load().find(x=>x.id===current);if(!w){view='applications';applications();return}const link=applicationLink(w);app.innerHTML=`<div class="top"><div><div class="eyebrow">我的投递 / ${esc(w.source.company)}</div><h1>${esc(w.source.title)}</h1><p class="muted">${esc([w.source.audience,w.source.category].filter(Boolean).join(' · '))}</p></div><div class="actions">${link?external(link,'我的申请'):''}<button data-flow="application-link">${link?'管理申请入口':'关联我的申请'}</button><button data-view="applications">返回列表</button></div></div><section class="process-panel"><div class="row"><h3>岗位进程</h3><button data-flow="new-node">＋ 更新进程</button></div>${nodeStrip(w)}</section><div class="workspace-grid"><section class="panel"><div class="row"><h2>职位描述</h2>${external(w.source.url,'岗位原页')}</div><div class="reading jd" style="margin-top:20px">${jd(w.source)}</div></section><section class="panel"><h2>岗位材料</h2><p class="muted" style="margin:12px 0 24px">暂未关联岗位简历</p><h3 style="margin-bottom:12px">准备笔记</h3><textarea id="notes" aria-label="当前岗位准备笔记" placeholder="记录这个岗位的准备内容…">${esc(w.notes)}</textarea><div class="row" style="margin-top:14px"><small id="savehint">${w.notes?'已保存':''}</small><button data-action="save-notes" class="primary">保存笔记</button></div></section></div>`};
function nodeDetail(id,owner){const w=load().find(x=>x.id===owner),n=nodes(w).find(x=>x.id===id);show(n.name,`<dl class="facts"><dt>记录时间</dt><dd>${esc(new Date(n.time).toLocaleString('zh-CN'))}</dd><dt>进展来源</dt><dd>${esc(n.origin||'用户记录')}</dd></dl>${n.url?external(n.url,'查看原始来源'):'<p class="muted">此节点由用户记录，未附外部凭据。</p>'}${n.reference?`<div class="divider"></div><small>创建时的岗位依据</small><p>${external(n.reference,'官网 JD')}</p>`:''}`)}
function linkForm(){const w=load().find(x=>x.id===current);show('关联我的申请',`<form id="application-link-form"><p class="muted helper">填写登录招聘网站后，“我的申请 / 投递记录”页面的链接。</p><label>${esc(w.source.company)} · 个人投递页面<input name="url" type="url" required value="${esc(applicationLink(w))}" placeholder="https://…"></label><p class="helper muted">同公司的工作台共用这个入口，与岗位原页分别保存。</p><p class="form-error"></p><button type="submit" class="primary">保存入口</button></form>`)}
function newNode(){show('记录岗位进展',`<form id="node-form"><div class="form-grid"><label>实际进展<input name="name" required maxlength="60" placeholder="例如：已投递、笔试、一面"></label><label>发生时间<input name="time" type="datetime-local" required></label></div><label>来源说明<input name="origin" maxlength="160" placeholder="例如：面试邀请邮件 / 官网提交回执 / 本人确认"></label><label>原始来源链接（选填）<input name="url" type="url" placeholder="邮件或官网页面链接"></label><p class="helper muted">只记录已发生或已收到通知的进展；未附链接时保留为用户确认。</p><p class="form-error"></p><button type="submit" class="primary">保存进展</button></form>`)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const take=()=>{e.preventDefault();e.stopImmediatePropagation()};if(b.dataset.action==='create'){take();const items=load();let w=items.find(x=>x.source.url===S.url);if(!w){w={id:crypto.randomUUID(),createdAt:new Date().toISOString(),source:structuredClone(S),notes:'',stage:'准备投递'};items.push(w);save(items)}modal.close();current=w.id;view='workspace';render();toast('工作台已打开');return}if(b.dataset.company){take();companyDetail(b.dataset.company);return}if(b.dataset.addCompany){take();addJob(b.dataset.addCompany);return}if(b.dataset.job){take();S=collected().find(x=>x.url===b.dataset.job);review();return}if(b.dataset.mode){take();switchMode(b.dataset.mode);return}if(b.dataset.node){take();nodeDetail(b.dataset.node,b.dataset.owner);return}if(b.dataset.flow){take();({back:backScreen,parse:parseLink,'application-link':linkForm,'new-node':newNode})[b.dataset.flow]?.()}},true);
document.addEventListener('submit',e=>{if(!['capture-form','parsed-form','application-link-form','node-form'].includes(e.target.id))return;e.preventDefault();e.stopImmediatePropagation();const f=e.target,d=new FormData(f);try{if(f.id==='capture-form'||f.id==='parsed-form'){if(f.id==='capture-form'&&mode==='link'){parseLink();return}const j={...(f.id==='parsed-form'?parsedMetadata:{}),company:String(d.get('company')).trim(),title:String(d.get('title')).trim(),url:validLink(d.get('url')||draft.url),captureMethod:f.id==='parsed-form'?(parsedMetadata?.captureMethod||'链接解析'):'手动添加',capturedOn:new Date().toISOString(),audience:f.id==='parsed-form'?(parsedMetadata?.audience||''):'',category:f.id==='parsed-form'?(parsedMetadata?.category||''):'',sections:[{title:'职位描述与要求',text:String(d.get('jd')).trim()}]};if(!j.company||!j.title||j.sections[0].text.length<20)throw Error('请完整填写岗位资料');keepJob(j);review();return}const items=load(),w=items.find(x=>x.id===current);if(f.id==='application-link-form'){const url=validLink(d.get('url'));if(url===w.source.url||companies.some(c=>c.url===url))throw Error('这里需要个人投递记录页面，不能使用岗位详情或岗位列表链接。');const links=JSON.parse(localStorage.getItem('career-company-applications-v1')||'{}');links[w.source.company]=url;localStorage.setItem('career-company-applications-v1',JSON.stringify(links))}else{const time=new Date(d.get('time'));if(!String(d.get('name')).trim()||isNaN(time))throw Error('请填写进展与时间');w.nodes=[...nodes(w),{id:crypto.randomUUID(),name:String(d.get('name')).trim(),time:time.toISOString(),origin:String(d.get('origin')).trim()||'用户确认',url:d.get('url')?validLink(d.get('url')):''}];w.stage=w.nodes.at(-1).name;save(items)}modal.close();render();toast('已保存')}catch(error){const target=f.querySelector('.form-error,#capture-error');if(target)target.textContent=error.message;else toast(error.message)}},true);
render();
