const marketIcon=(name)=>{const paths={spark:'<path d="M12 2c1.2 6.2 3.8 8.8 10 10-6.2 1.2-8.8 3.8-10 10C10.8 15.8 8.2 13.2 2 12c6.2-1.2 8.8-3.8 10-10z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',briefcase:'<rect x="3" y="7" width="18" height="14" rx="3"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12c5 4 13 4 18 0M10 13h4"/>',bookmark:'<path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16l-6-4z"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0z"/><circle cx="12" cy="10" r="2.5"/>'};return `<svg class="market-icon icon-${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||''}</svg>`};
const app=document.querySelector('#app'),modal=document.querySelector('#modal');let S=window.tencentSnapshot;
const KEY='career-job-workspaces-v1';let current=null,view='market';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return []}}
function save(items){localStorage.setItem(KEY,JSON.stringify(items))}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',2500)}
function show(title,body){document.querySelector('#modalbody').innerHTML=`<h2>${esc(title)}</h2>${body}`;modal.showModal()}
document.querySelector('#closemodal').onclick=()=>modal.close();
const external=(url,label)=>`<a class="button" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
const jd=s=>s.sections.map(x=>`<h3>${esc(x.title)}</h3><div>${esc(x.text)}</div>`).join('');

const companies=[
 {name:'腾讯',industry:'互联网 / 科技',batch:'2027校招',cities:'深圳、北京、上海、广州、成都等',roles:'技术 / 产品 / 游戏策划 / 投资分析',url:'https://join.qq.com/post.html',source:'腾讯官网',date:'09-14'},
 {name:'云和恩墨',industry:'互联网 / 科技',batch:'2027校招',cities:'北京、石家庄、上海、南京等',roles:'数据库技术顾问 / 销售 / 人力 / 投标',url:'https://app.mokahr.com/campus-recruitment/enmotech/47098',source:'招聘汇总',date:'09-13'},
 {name:'兆易创新',industry:'通信 / 电子',batch:'2027校招',cities:'苏州、合肥、武汉、深圳等',roles:'研发 / 测试 / 硬件 / 市场 / 供应链',url:'https://app.mokahr.com/campus-recruitment/gigadevice/92215',source:'招聘汇总',date:'09-13'},
 {name:'中通服咨询设计研究院',industry:'互联网 / 科技',batch:'2027校招',cities:'北京、南京、广州、成都等',roles:'通信 / 软件 / 工程咨询 / 人工智能',url:'https://cicdi2027.zhaopin.com/',source:'招聘汇总',date:'09-13'},
 {name:'盛吉盛半导体',industry:'通信 / 电子',batch:'2027校招',cities:'北京、上海、武汉、合肥等',roles:'机械 / 工艺 / 算法 / 软件 / 硬件',url:'https://sgssemi.zhiye.com/campus',source:'招聘汇总',date:'09-13'},
 {name:'东方空间',industry:'制造业',batch:'2027校招',cities:'北京、上海、西安、无锡等',roles:'飞控算法 / 软件 / 结构 / 发动机',url:'https://orienspace.zhiye.com/',source:'招聘汇总',date:'09-13'}
];
let marketTab='companies',filter={q:'',industry:'全部行业',batch:'全部批次',city:'全部地点'};
function collected(){let added=[];try{added=JSON.parse(localStorage.getItem('career-collected-jobs-v1')||'[]')}catch{}return added.some(x=>x.url===window.tencentSnapshot.url)?added:[window.tencentSnapshot,...added]}
function dock(){return `<div class="dock"><span style="color:#4278f6;font-size:25px">✧</span><input aria-label="Agent 输入" placeholder="${view==='workspace'?'围绕这个岗位开始准备…':'让 Agent 帮你找机会…'}" disabled><small>Agent 尚未连接</small></div>`}
function render(){document.querySelectorAll('nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===(view==='workspace'?'applications':view)));if(view==='market')market();else if(view==='review'){view='market';market();review()}else if(view==='applications')applications();else workspace();app.innerHTML+=dock()}
function market(){app.innerHTML=`<div class="top"><div><h1>岗位市场</h1><p class="muted">发现招聘机会，选择下一站，开启更多可能。</p></div><button class="primary" data-action="add-job">＋ 添加官网岗位</button></div><div class="market-tabs"><button data-tab="companies" class="${marketTab==='companies'?'selected':''}">${marketIcon('briefcase')}招聘目录</button><button data-tab="jobs" class="${marketTab==='jobs'?'selected':''}">${marketIcon('bookmark')}已收藏岗位 <small>${collected().length}</small></button><button data-tab="favorites" class="${marketTab==='favorites'?'selected':''}">${marketIcon('heart')}我的收藏</button></div><section class="catalog panel"><div class="filters"><input type="search" id="search" value="${esc(filter.q)}" placeholder="搜索公司、岗位方向" aria-label="搜索公司">${[['industry','行业',['全部行业','互联网 / 科技','通信 / 电子','制造业']],['batch','批次',['全部批次','2027校招']],['city','地点',['全部地点','北京','上海','深圳','南京','成都','武汉']]].map(([key,label,opts])=>`<select aria-label="${label}" data-filter="${key}">${opts.map(x=>`<option ${filter[key]===x?'selected':''}>${x}</option>`).join('')}</select>`).join('')}<button data-action="reset-filters">重置</button></div><div id="results"></div></section><p class="catalog-foot">预览数据 · 6 条目录记录，非全量数据库。地点与方向为摘要；具体要求以官网为准。</p>`;results()}
function favorites(){try{return JSON.parse(localStorage.getItem('career-company-favorites-v1')||'[]')}catch{return []}}
function results(){const q=filter.q.toLowerCase(),jobs=marketTab==='jobs';let rows=jobs?collected():companies;rows=rows.filter(c=>{const text=jobs?[c.company,c.title,c.category].join(' '):[c.name,c.roles].join(' ');return text.toLowerCase().includes(q)&&(jobs||((filter.industry==='全部行业'||c.industry===filter.industry)&&(filter.city==='全部地点'||c.cities.includes(filter.city))&&(filter.batch==='全部批次'||c.batch===filter.batch)))&&(marketTab!=='favorites'||favorites().includes(c.name))});document.querySelector('#results').innerHTML=`<div class="result-count">${rows.length} ${jobs?'个岗位':'条招聘记录'}</div>${jobs?rows.map(c=>`<article class="job-row"><div><h3>${esc(c.title)}</h3><p class="muted">${esc(c.company)} · ${esc(c.audience||'招聘类型未填写')}</p></div><span class="tag">${c.captureMethod==='手动添加'?'手动添加':'官网快照'}</span><button data-job="${esc(c.url)}">查看岗位 →</button></article>`).join(''):`<div class="table-scroll"><table><colgroup><col class="col-company"><col class="col-batch"><col class="col-role"><col class="col-city"><col class="col-date"><col class="col-action"></colgroup><thead><tr><th>公司 / 行业</th><th>招聘批次</th><th>岗位方向</th><th>地点摘要</th><th>更新</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><div class="directory-company"><span class="directory-mark" aria-hidden="true">${c.name==='腾讯'?'Tencent':esc(c.name.slice(0,2))}</span><div><b>${esc(c.name)}</b><small>${esc(c.industry)}</small></div></div></td><td><span class="tag">${c.batch}</span></td><td>${esc(c.roles)}</td><td><div class="location-summary">${marketIcon('pin')}<span>${esc(c.cities)}<small>多地可选</small></span></div></td><td><span class="update-date">${marketIcon('clock')}<span>${c.date}</span></span></td><td><button data-company="${esc(c.name)}">查看 →</button><button class="quick-collaborate" data-co-select-company="${esc(c.name)}" aria-label="围绕${esc(c.name)}协作" title="围绕此公司协作">${marketIcon('spark')}</button><button class="quick-favorite ${favorites().includes(c.name)?'is-saved':''}" data-quick-favorite="${esc(c.name)}" aria-label="${favorites().includes(c.name)?'取消收藏':'收藏'}${esc(c.name)}" aria-pressed="${favorites().includes(c.name)}" title="${favorites().includes(c.name)?'取消收藏':'收藏公司'}">${marketIcon('bookmark')}</button></td></tr>`).join('')}</tbody></table></div>`}${rows.length?'':'<div class="empty">没有符合条件的记录</div>'}`}
function companyDetail(name){const c=companies.find(x=>x.name===name);show(c.name,`<div class="tags"><span class="tag">${c.industry}</span><span class="tag">${c.batch}</span></div><dl class="facts"><dt>岗位方向</dt><dd>${esc(c.roles)}</dd><dt>地点摘要</dt><dd>${esc(c.cities)}</dd><dt>信息来源</dt><dd>${c.source} · 2026-${c.date}</dd></dl><div class="actions">${external(c.url,'打开官网岗位列表')}<button data-favorite="${esc(c.name)}">${favorites().includes(c.name)?'取消收藏':'收藏公司'}</button></div><div class="divider"></div><h3>已收集岗位</h3>${collected().filter(j=>j.company===c.name).map(j=>`<div class="job-row"><span>${esc(j.title)}</span><button data-job="${esc(j.url)}">查看岗位 →</button></div>`).join('')||'<p class="muted" style="margin:15px 0">尚未添加具体岗位。</p>'}<button data-add-company="${esc(c.name)}">＋ 添加这个公司的岗位</button>`)}
function review(){show(S.title,`<p class="muted" style="margin:8px 0">${esc(S.company)} · ${esc(S.audience||'')}</p><div class="reading jd">${jd(S)}</div><div class="detail-footer">${external(S.url,'岗位原页')}<button data-action="create" class="primary">${load().some(w=>w.source.url===S.url)?'进入工作台':'创建工作台'}</button></div>`)}
function addJob(company=''){show('添加官网岗位',`<form id="add-job-form"><p class="muted" style="margin:12px 0 20px">复制官网的岗位链接和 JD，保存后即可开始准备。</p><div class="form-grid"><label>公司<input name="company" required maxlength="100" value="${esc(company)}"></label><label>岗位名称<input name="title" required maxlength="180"></label></div><label>岗位详情链接<input name="url" type="url" required placeholder="https://…"></label><label>职位描述与要求<textarea name="jd" required minlength="20" maxlength="60000" placeholder="粘贴这个岗位的职责、要求等内容"></textarea></label><p id="form-error" role="alert"></p><button type="submit" class="primary">保存并查看岗位</button><small style="display:block;margin-top:12px">当前支持手动添加，自动读取官网尚未接入。</small></form>`)}
function applications(){const items=load();app.innerHTML=`<div class="top"><div><div class="eyebrow">APPLICATIONS / 你的岗位进程</div><h1>我的投递</h1><p class="muted">从准备开始，留下每一个已经发生的进展。</p></div><button data-view="market">发现新的机会 →</button></div>${items.length?items.map(w=>`<article class="jobcard" data-workspace="${esc(w.id)}" role="button" tabindex="0"><div class="row"><div class="identity"><div class="logo">${esc(w.source.company.slice(0,2))}</div><div><h2>${esc(w.source.title)}</h2><small>${esc(w.source.company)} · ${esc(w.source.audience)}</small></div></div><span class="tag">准备投递　→</span></div><div class="timeline"><span>准备投递</span></div></article>`).join(''):'<section class="panel empty">还没有岗位工作台。到岗位市场，选中一个岗位后开始准备。</section>'}`}

function workspace(){const w=load().find(x=>x.id===current);if(!w){view='applications';applications();return}app.innerHTML=`<div class="top"><div><div class="eyebrow">我的投递 / ${esc(w.source.company)}</div><h1>${esc(w.source.title)}</h1><p class="muted">${esc(w.source.audience||'')} ${esc(w.source.category||'')}</p></div><div class="actions">${external(w.source.url,'岗位原页')}<button data-view="applications">返回</button></div></div><div class="progress-strip"><span>● 准备投递</span></div><div class="workspace-grid"><section class="panel"><h2>职位描述</h2><div class="reading jd" style="margin-top:20px">${jd(w.source)}</div></section><section class="panel"><h2>岗位材料</h2><p class="muted" style="margin:12px 0 24px">暂未关联岗位简历</p><h3 style="margin-bottom:12px">准备笔记</h3><textarea id="notes" aria-label="当前岗位准备笔记" placeholder="记录针对这个岗位的准备内容…">${esc(w.notes)}</textarea><div class="row" style="margin-top:14px"><small id="savehint">${w.notes?'已保存':''}</small><button data-action="save-notes" class="primary">保存笔记</button></div></section></div>`}
document.addEventListener('input',e=>{if(e.target.id==='search'){filter.q=e.target.value;results()}});
document.addEventListener('change',e=>{if(e.target.dataset.filter){filter[e.target.dataset.filter]=e.target.value;results()}});
document.addEventListener('submit',e=>{if(e.target.id!=='add-job-form')return;e.preventDefault();try{const data=new FormData(e.target),url=new URL(data.get('url'));if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('请输入正常的 HTTP 或 HTTPS 岗位链接');url.hash='';for(const k of ['company','title','jd'])if(!data.get(k).trim())throw Error('请填写公司、岗位名称和 JD');const j={company:data.get('company').trim(),title:data.get('title').trim(),url:url.href,jobId:url.searchParams.get('postid')||'',audience:'',category:'',capturedOn:new Date().toISOString(),captureMethod:'手动添加',sections:[{title:'职位描述与要求',text:data.get('jd').trim()}]};const items=collected().filter(x=>x.url!==j.url);items.push(j);localStorage.setItem('career-collected-jobs-v1',JSON.stringify(items));S=j;modal.close();marketTab='jobs';view='market';render();review()}catch(err){document.querySelector('#form-error').textContent=err.message}});
document.addEventListener('keydown',e=>{if(e.target.dataset.workspace&&e.key==='Enter')e.target.click()});
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-workspace]');if(!b)return;try{if(b.dataset.tab){marketTab=b.dataset.tab;render();return}if(b.dataset.company){companyDetail(b.dataset.company);return}if(b.dataset.job){S=collected().find(x=>x.url===b.dataset.job);modal.close();review();return}if(b.dataset.addCompany){modal.close();addJob(b.dataset.addCompany);return}if(b.dataset.favorite){let fs=favorites();fs=fs.includes(b.dataset.favorite)?fs.filter(x=>x!==b.dataset.favorite):[...fs,b.dataset.favorite];localStorage.setItem('career-company-favorites-v1',JSON.stringify(fs));modal.close();render();return}if(b.dataset.view){view=b.dataset.view;render();return}if(b.dataset.workspace){current=b.dataset.workspace;view='workspace';render();return}switch(b.dataset.action){case'add-job':addJob();break;case'reset-filters':filter={q:'',industry:'全部行业',batch:'全部批次',city:'全部地点'};render();break;case'review':view='review';render();break;case'favorite':{const yes=localStorage.getItem('career-tencent-favorite')!=='yes';localStorage.setItem('career-tencent-favorite',yes?'yes':'no');b.textContent=yes?'★ 已收藏':'☆ 收藏公司';break}case'create':{modal.close();const items=load();let w=items.find(x=>x.source.url===S.url);if(!w){w={id:crypto.randomUUID(),createdAt:new Date().toISOString(),source:structuredClone(S),notes:'',stage:'准备投递'};items.push(w);save(items)}current=w.id;view='workspace';render();toast('岗位工作台已打开 · 尚未投递');break}case'save-notes':{const items=load(),w=items.find(x=>x.id===current);w.notes=document.querySelector('#notes').value;save(items);document.querySelector('#savehint').textContent='笔记已保存在当前浏览器';toast('当前岗位笔记已保存');break}case'source':{const w=load().find(x=>x.id===current);show('腾讯官网 JD · 保存版本',`<div class="jd">${jd(w.source)}</div>`);break}}}catch(error){toast('操作未保存：'+error.message)}});
// Browser adapter handoff: a public, selected Tencent JD only; never arbitrary HTML or page scripts.
if(location.hash.startsWith('#capture=')){
 try{
  const incoming=JSON.parse(decodeURIComponent(location.hash.slice(9))),url=new URL(incoming.url);
  if(url.origin!=='https://join.qq.com'||url.pathname!=='/post_detail.html'||url.searchParams.get('postid')!==incoming.jobId||!/^\d{1,30}$/.test(incoming.jobId))throw Error('岗位来源或编号不一致');
  for(const key of ['company','title','category','audience','interview','capturedOn','captureMethod'])if(typeof incoming[key]!=='string'||incoming[key].length>250)throw Error('字段不完整');
  if(!Array.isArray(incoming.sections)||incoming.sections.length!==3||incoming.sections.some(s=>typeof s.title!=='string'||typeof s.text!=='string'||s.text.length<20||s.text.length>20000))throw Error('岗位正文不完整');
  if(!Array.isArray(incoming.departments)||incoming.departments.some(d=>typeof d!=='string'||d.length>150))throw Error('部门字段无效');
  S={schema:1,company:incoming.company,title:incoming.title,jobId:incoming.jobId,url:url.origin+url.pathname+'?postid='+incoming.jobId,listUrl:'https://join.qq.com/post.html',capturedOn:incoming.capturedOn,captureMethod:incoming.captureMethod,category:incoming.category,audience:incoming.audience,interview:incoming.interview,departments:incoming.departments,sections:incoming.sections.map(s=>({title:s.title,text:s.text}))};
  sessionStorage.setItem('career-market-capture-v1',JSON.stringify(S));view='review';
 }catch(e){toast('读取结果未接收：'+e.message)}
 history.replaceState(null,'',location.pathname);
}else{try{const captured=JSON.parse(sessionStorage.getItem('career-market-capture-v1')||'null');if(captured)S=captured}catch{}}
render();

document.addEventListener('click',e=>{const b=e.target.closest('[data-quick-favorite]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const name=b.dataset.quickFavorite,items=favorites(),saved=!items.includes(name);localStorage.setItem('career-company-favorites-v1',JSON.stringify(saved?[...items,name]:items.filter(n=>n!==name)));results();toast(saved?'已收藏 '+name:'已取消收藏 '+name)},true);
