const api=window.careerDesktop;let state=null,agentVisible=true,noticeTimer;
const $=s=>document.querySelector(s);
function notify(text){$('#notice').textContent=text;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,5000)}
async function run(action,payload){try{const result=await api.command(action,payload);if(result)paint(result)}catch(e){notify(e.message.replace(/^Error invoking remote method[^:]*: /,''))}}
function paint(next){state=next;const browsing=state.mode==='browser';$('#home').hidden=browsing;$('#browser').hidden=!browsing;$('#heading').textContent=browsing?'官网浏览器':'从这里，继续下一步。';$('#browser-entry').classList.toggle('selected',browsing);$('[data-action="home"]').classList.toggle('selected',!browsing);
 const nav=$('#page-nav'),pages=$('#pages');if(!nav.children.length){for(const page of state.pages){const b=document.createElement('button');b.textContent=page.label;b.onclick=()=>run('page',page.id);nav.append(b);const card=document.createElement('button');card.className='page-card';const title=document.createElement('strong');title.textContent=page.label;const hint=document.createElement('small');hint.textContent=page.available?'打开页面 →':'等待已确认版本的源码';card.append(title,hint);card.onclick=()=>run('page',page.id);pages.append(card)}}
 const tabs=$('#tabs');tabs.replaceChildren();for(const tab of state.tabs){const box=document.createElement('div');box.className='tab'+(tab.id===state.active?' active':'');const select=document.createElement('button');select.className='tab-label';select.textContent=(tab.loading?'· ':'')+tab.title;select.title=tab.title;select.setAttribute('role','tab');select.setAttribute('aria-selected',String(tab.id===state.active));select.onclick=()=>run('select',tab.id);const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','关闭 '+tab.title);close.onclick=()=>run('close',tab.id);box.append(select,close);tabs.append(box)}
 const tab=state.tabs.find(t=>t.id===state.active);if(document.activeElement!==$('#address'))$('#address').value=tab?.url||'';$('#context-title').textContent=tab?.title||'尚未打开';try{$('#context-domain').textContent=new URL(tab.url).host}catch{$('#context-domain').textContent=''}$('#browser-error').hidden=!tab?.error;$('#browser-error').textContent=tab?.error||'';$('[data-action="back"]').disabled=!tab?.back;$('[data-action="forward"]').disabled=!tab?.forward;const reload=$('[data-action="reload"], [data-action="stop"]');reload.dataset.action=tab?.loading?'stop':'reload';reload.textContent=tab?.loading?'×':'↻';reload.setAttribute('aria-label',tab?.loading?'停止加载':'刷新');if(state.notice&&state.notice!==paint.lastNotice){notify(state.notice);paint.lastNotice=state.notice}requestAnimationFrame(bounds)}
function bounds(){if(!state||state.mode!=='browser')return;const r=$('#browser-surface').getBoundingClientRect();api.command('bounds',{x:r.x,y:r.y,width:r.width,height:r.height}).catch(()=>{})}
new ResizeObserver(bounds).observe($('#browser-surface'));
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)run(b.dataset.action)});
$('#home-url').onsubmit=e=>{e.preventDefault();run('open',e.target.querySelector('input').value)};
$('#address-form').onsubmit=e=>{e.preventDefault();$('#address').blur();run('navigate',$('#address').value)};
$('#tencent').onclick=()=>run('open','https://join.qq.com/post.html');
$('#new-tab').onclick=()=>{run('home');$('#home-url input').focus()};
$('#browser-entry').onclick=()=>state?.active?run('select',state.active):$('#home-url input').focus();
$('#agent-toggle').onclick=()=>{agentVisible=!agentVisible;$('#agent').hidden=!agentVisible;$('#agent-toggle').setAttribute('aria-pressed',String(agentVisible));requestAnimationFrame(bounds)};
api.onState(paint);run('state');
