/* Resume document v1. UI operations share one mutation/undo/persistence boundary. */
(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=x=>structuredClone(x),id=()=>crypto.randomUUID(),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='career-resume-document-v1', templates=[['modern','清朗 · 专业单栏','清晰的层次，适合大多数求职场景'],['classic','素简 · 经典单栏','居中标题，克制的黑白表达'],['two','并行 · 双栏布局','同一份内容，更紧凑的双栏阅读']];
let doc,sectionId='identity',itemId=null,quill=null,undo=[],redo=[],typingTimer,saveTimer,renderTimer,saving=Promise.resolve(),zoom=0.8,autofit=true,dirty=false,revision=0,dragId=null,toastTimer,renderGeneration=0;
const rich=text=>({ops:[{insert:text+'\n'}]}), item=(title,meta,dates,text)=>({id:id(),title,meta,dates,body:rich(text)});
function fromProfile(p){const r=p?.records||{},basic=r.basic?.[0]||{},intent=r.intent?.[0]||{};const sec=[];const names={advantage:'个人优势',work:'工作 / 实习经历',project:'项目经历',education:'教育经历',skills:'专业技能',cert:'资格证书',club:'社团 / 组织经历',volunteer:'志愿者经历',works:'作品与链接'};
for(const key of Object.keys(names)){const arr=r[key]||[];if(!arr.length)continue;sec.push({id:id(),title:names[key],visible:true,breakBefore:false,items:arr.map(v=>item(v.company||v.school||v.name||'', [v.role,v.major,v.degree,v.tags,v.issuer].filter(Boolean).join(' · '),v.start?`${v.start} — ${v.ongoing?'至今':v.end||''}`:v.date||'', [v.description,v.achievement,v.url,v.rank].filter(Boolean).join('\n')))})}
if(!sec.length)sec.push({id:id(),title:'个人优势',visible:true,items:[item('','','','填写你的经历、能力和成果。')]});
return {schema:1,id:id(),name:(basic.name||'我的')+' · 基础简历',identity:{name:basic.name||'你的姓名',role:intent.role||'求职方向',contact:[basic.city,basic.phone,basic.email].filter(Boolean).join('  |  '),photo:''},style:{template:'modern',font:'sans',size:11,leading:1.5,margin:18,gap:17,color:'#355d82'},sections:sec,createdAt:new Date().toISOString()};}
function notify(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4000)}
function currentSection(){return doc.sections.find(s=>s.id===sectionId)}function currentItem(){return currentSection()?.items.find(i=>i.id===itemId)}
function setStatus(t,warning=false){$('#save-state').textContent=t;$('#save-state').classList.toggle('warn',warning)}
function historyButtons(){$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length}
function checkpoint(){clearTimeout(typingTimer);typingTimer=null;undo.push(clone(doc));if(undo.length>80)undo.shift();redo=[];historyButtons()}
function changed(){revision++;dirty=true;doc.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(doc))}catch{}setStatus('正在保存…');clearTimeout(saveTimer);saveTimer=setTimeout(persist,650);scheduleRender()}
function mutate(fn,refresh=true){checkpoint();fn(doc);changed();if(refresh)renderPanel()}
function typed(fn){if(!typingTimer)checkpoint();fn();changed();clearTimeout(typingTimer);typingTimer=setTimeout(()=>{typingTimer=null},750)}
async function persist(){clearTimeout(saveTimer);const snapshot=clone(doc),r=revision;const task=async()=>{try{const res=await fetch('/api/resumes/'+snapshot.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});if(!res.ok)throw Error();if(r===revision){dirty=false;setStatus('已保存到本机 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}))}return true}catch{setStatus('保存失败 · 已保留浏览器草稿',true);return false}};saving=saving.then(task,task);return saving}
function applyHistory(from,to){if(!from.length)return;clearTimeout(typingTimer);typingTimer=null;to.push(clone(doc));doc=from.pop();changed();renderAll()}
function sanitize(html){const t=document.createElement('template');t.innerHTML=html;for(const el of [...t.content.querySelectorAll('*')]){if(!['P','BR','STRONG','B','EM','I','U','S','SPAN','A','OL','UL','LI','SUB','SUP'].includes(el.tagName)){el.replaceWith(...el.childNodes);continue}if(el.classList.contains('ql-size-small'))el.style.fontSize='0.75em';if(el.classList.contains('ql-size-large'))el.style.fontSize='1.5em';for(const a of [...el.attributes])if(!['style','href'].includes(a.name))el.removeAttribute(a.name);if(el.hasAttribute('href')&&!/^(https?:|mailto:)/i.test(el.getAttribute('href')))el.removeAttribute('href');const st=el.style;const values={color:st.color,fontSize:st.fontSize,textAlign:st.textAlign};el.removeAttribute('style');for(const [k,v]of Object.entries(values))if(v)el.style[k]=v;}return t.innerHTML}
const scratch=document.createElement('div');scratch.style.display='none';document.body.append(scratch);const converter=new Quill(scratch,{modules:{toolbar:false},formats:['bold','italic','underline','strike','color','size','list','align','link']});
function htmlOf(delta){converter.setContents(delta||rich(''),'silent');return sanitize(converter.getSemanticHTML())}
function choose(sec,it){sectionId=sec;const s=currentSection();itemId=it||s?.items[0]?.id||null;tab('content');renderPanel()}
function renderOutline(){$('#outline').innerHTML=`<div class="outline-row ${sectionId==='identity'?'selected':''}"><button class="select-section" data-select="identity">◉　姓名与联系方式</button></div>`+doc.sections.map(s=>`<div class="outline-row ${sectionId===s.id?'selected':''}" draggable="true" data-drag="${s.id}"><input aria-label="显示${esc(s.title)}" type="checkbox" data-visible="${s.id}" ${s.visible?'checked':''}><button class="select-section ${!s.visible?'muted':''}" data-select="${s.id}">${esc(s.title)}</button><button class="arrow" data-move="${s.id}:-1" aria-label="上移${esc(s.title)}">↑</button><button class="arrow" data-move="${s.id}:1" aria-label="下移${esc(s.title)}">↓</button></div>`).join('')}
function renderPanel(){renderOutline();const out=$('#selected-editor');quill=null;if(sectionId==='identity'){out.innerHTML=`<h3>姓名与联系方式</h3><label>姓名<input data-identity="name" value="${esc(doc.identity.name)}"></label><label>求职方向<input data-identity="role" value="${esc(doc.identity.role)}"></label><label>联系方式<textarea rows="3" data-identity="contact">${esc(doc.identity.contact)}</textarea></label><label>照片（选填）</label><div class="photo-controls"><input id="photo-upload" type="file" accept="image/png,image/jpeg,image/webp" aria-label="上传照片">${doc.identity.photo?'<button id="remove-photo">移除</button>':''}</div><p class="hint">仅修改这份简历，不会自动修改个人资料。</p>`;return}
let s=currentSection();if(!s){sectionId='identity';renderPanel();return}if(!s.items.some(i=>i.id===itemId))itemId=s.items[0]?.id;const it=currentItem();out.innerHTML=`<label>模块名称<input id="section-title" value="${esc(s.title)}"></label><label class="checkline"><input id="break-before" type="checkbox" ${s.breakBefore?'checked':''}>在此模块前分页</label><div class="itemtabs">${s.items.map((v,i)=>`<button data-item="${v.id}" class="${v.id===itemId?'active':''}">${esc(v.title||'第 '+(i+1)+' 条')}</button>`).join('')}<button id="add-item" aria-label="添加经历">＋ 添加</button></div>${it?`<label>经历 / 项目名称<input id="item-title" value="${esc(it.title)}" placeholder="选填，例如公司或项目名称"></label><label>职位 / 专业 / 补充信息<input id="item-meta" value="${esc(it.meta)}"></label><label>时间<input id="item-dates" value="${esc(it.dates)}" placeholder="2025.09 — 至今"></label><label>内容描述</label><div id="rich-toolbar"><span class="ql-formats"><button class="ql-bold" aria-label="加粗"></button><button class="ql-italic" aria-label="斜体"></button><button class="ql-underline" aria-label="下划线"></button><button class="ql-strike" aria-label="删除线"></button></span><span class="ql-formats"><select class="ql-color" aria-label="文字颜色"></select><select class="ql-size" aria-label="局部字号"><option value="small"></option><option selected></option><option value="large"></option></select></span><span class="ql-formats"><button class="ql-list" value="bullet" aria-label="项目符号"></button><button class="ql-list" value="ordered" aria-label="编号"></button><select class="ql-align" aria-label="对齐"></select><button class="ql-link" aria-label="链接"></button><button class="ql-clean" aria-label="清除格式"></button></span></div><div id="rich-editor" aria-label="经历内容"></div><div class="editorfoot"><button id="item-up">条目上移</button><button id="item-down">下移</button><button id="delete-item" class="danger">删除条目</button></div>`:'<div class="empty">添加一条经历，开始编辑。</div>'}<button id="delete-section" class="wide danger">移除这个模块</button>`;
if(it){quill=new Quill('#rich-editor',{theme:'snow',modules:{toolbar:'#rich-toolbar',history:{userOnly:true}},formats:['bold','italic','underline','strike','color','size','list','align','link']});quill.setContents(it.body,'silent');quill.on('text-change',(_,__,source)=>{if(source==='user')typed(()=>{it.body=quill.getContents()})})}}
function tab(name){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.toolpanel').forEach(p=>p.hidden=p.id!=='panel-'+name);if(name==='layout')renderStyle()}
function renderStyle(){for(const k of ['font','size','leading','margin','gap','color'])$('#'+k).value=doc.style[k];for(const k of ['size','leading','margin','gap'])$('#'+k+'-value').textContent=doc.style[k]+({size:' pt',leading:' 倍',margin:' mm',gap:' px'}[k]);$('#template-list').innerHTML=templates.map(([key,name,desc])=>`<button class="template ${doc.style.template===key?'active':''}" data-template="${key}"><div class="mini-paper"><div>${'<i></i>'.repeat(15)}</div>${key==='two'?'<div>'+ '<i></i>'.repeat(15)+'</div>':''}</div><strong>${name}</strong><small>${desc}</small></button>`).join('')}
function renderAll(){$('#doc-name').value=doc.name;renderPanel();renderStyle();historyButtons();scheduleRender()}
function make(tag,cls,html,sec,it){const e=document.createElement(tag);e.className='atom '+cls;e.innerHTML=html;e.dataset.section=sec;if(it)e.dataset.item=it;return e}
function atoms(){const arr=[],p=doc.identity;arr.push(make('div','identity',`${p.photo?`<img class="photo" src="${p.photo}" alt="个人照片">`:''}<h1>${esc(p.name)}</h1><div class="role">${esc(p.role)}</div><div class="contact">${esc(p.contact)}</div>`,'identity'));
for(const s of doc.sections.filter(x=>x.visible)){const head=make('h2','sectionheading',esc(s.title),s.id);head.dataset.keep='true';head.dataset.break=s.breakBefore?'true':'false';arr.push(head);for(const i of s.items){if(i.title||i.dates){const el=make('div','entryhead',`<strong>${esc(i.title)}</strong><small>${esc(i.dates)}</small>`,s.id,i.id);el.dataset.keep='true';arr.push(el)}if(i.meta){const el=make('div','entrymeta',esc(i.meta),s.id,i.id);el.dataset.keep='true';arr.push(el)}const tmp=document.createElement('div');tmp.innerHTML=htmlOf(i.body);for(const child of [...tmp.children]){if(['UL','OL'].includes(child.tagName)){[...child.children].forEach((li,n)=>{const prefix=child.tagName==='OL'?(n+1)+'. ':'• ';const el=make('div','paragraph',`<p>${prefix}${li.innerHTML}</p>`,s.id,i.id);arr.push(el)})}else arr.push(make('div','paragraph',child.outerHTML,s.id,i.id))}}}return arr}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(renderPages,80)}
function measure(el){const cs=getComputedStyle(el);return el.getBoundingClientRect().height+parseFloat(cs.marginTop)+parseFloat(cs.marginBottom)}
function splitAtom(el,maxHeight){const texts=[];const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);while(w.nextNode())texts.push(w.currentNode);const total=texts.reduce((n,t)=>n+t.length,0);if(total<2)return null;function rangeEnd(r,n){let left=n;for(const t of texts){if(left<=t.length){r.setEnd(t,left);return}left-=t.length}}const original=el.innerHTML;let low=1,high=total-1,best=0;while(low<=high){const mid=(low+high)>>1;el.innerHTML=original;const ts=[];const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);while(walker.nextNode())ts.push(walker.currentNode);let n=mid,r=document.createRange();r.selectNodeContents(el);for(const t of ts){if(n<=t.length){r.setEnd(t,n);break}n-=t.length}const fragment=r.cloneContents();el.replaceChildren(fragment);if(measure(el)<=maxHeight){best=mid;low=mid+1}else high=mid-1}
el.innerHTML=original;if(!best)return null;let r=document.createRange();r.selectNodeContents(el);let n=best;const wa=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);while(wa.nextNode()){if(n<=wa.currentNode.length){r.setEnd(wa.currentNode,n);break}n-=wa.currentNode.length}const first=r.cloneContents();const rest=document.createRange();rest.selectNodeContents(el);rest.setStart(r.endContainer,r.endOffset);const second=rest.cloneContents();const next=el.cloneNode(false);next.append(second);el.replaceChildren(first);return next}
function renderPages(){clearTimeout(renderTimer);const host=$('#pages'),scroll=$('#paper-scroll');const oldTop=scroll.scrollTop;host.innerHTML='';const st=doc.style,margin=st.margin*96/25.4,max=1123-2*margin;let page,col,used=0,columnIndex=0,pageNumber=0;
function newPage(){pageNumber++;const wrap=document.createElement('div');wrap.className='pagewrap';page=document.createElement('section');page.className='sheet '+st.template;page.style.cssText=`padding:${margin}px;--accent:${st.color};--gap:${st.gap}px;font-family:${st.font==='serif'?'ResumeSerif':'ResumeSans'};font-size:${st.size*4/3}px;line-height:${st.leading}`;page.innerHTML='<div class="pagecols"><div class="column"></div>'+(st.template==='two'?'<div class="column"></div>':'')+`</div><div class="footer-page">${pageNumber}</div>`;wrap.append(page);host.append(wrap);columnIndex=0;col=page.querySelector('.column');used=0;return col}
function advance(forcePage=false){if(st.template==='two'&&columnIndex===0&&!forcePage){columnIndex=1;col=page.querySelectorAll('.column')[1];used=0}else newPage()}
newPage();const queue=atoms();for(let n=0;n<queue.length;n++){let a=queue[n];if(a.dataset.break==='true'&&used>0)advance(true);col.append(a);let h=measure(a);if(a.dataset.keep&&n+1<queue.length){let need=h;const temp=[];for(let j=n+1;j<queue.length&&j<n+4;j++){const c=queue[j].cloneNode(true);col.append(c);temp.push(c);need+=c.dataset.keep?measure(c):Math.min(measure(c),st.size*4/3*st.leading*2+5);if(!c.dataset.keep)break}temp.forEach(c=>c.remove());if(need>max-used&&used>0){a.remove();advance();col.append(a);h=measure(a)}}if(h>max+.5&&a.classList.contains('paragraph')&&max-used>st.size*4/3*st.leading*2){const rest=splitAtom(a,max-used);if(rest){queue.splice(n+1,0,rest);h=measure(a)}}if(h>max-used+.5&&used>0){a.remove();advance();col.append(a);h=measure(a)}if(h>max+.5&&a.classList.contains('paragraph')){const rest=splitAtom(a,max);if(rest)queue.splice(n+1,0,rest);h=measure(a)}used+=h;}
if(pageNumber>60)notify('文档较长，请减少单份简历内容');const chars=doc.sections.filter(s=>s.visible).reduce((t,s)=>t+s.items.reduce((v,i)=>v+i.body.ops.reduce((k,o)=>k+(typeof o.insert==='string'?o.insert.length:0),0),0),0);$('#page-count').textContent=`${pageNumber} 页 · A4`;$('#document-stats').textContent=chars+' 字';applyZoom();scroll.scrollTop=oldTop;renderGeneration++;}
function applyZoom(){if(autofit)zoom=Math.min(1,Math.max(.32,($('#paper-scroll').clientWidth-70)/794));$$('.pagewrap').forEach(w=>{w.style.width=794*zoom+'px';w.style.height=1123*zoom+'px';w.firstChild.style.transform=`scale(${zoom})`});$('#zoom-fit').textContent=Math.round(zoom*100)+'% · 适宽'}
function modal(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal()}
function confirmRemove(type){modal('移除'+(type==='section'?'模块':'条目'),'<p>将从这份简历中移除，可通过撤销恢复。个人资料不受影响。</p><button class="danger" id="confirm-remove">确认移除</button>');$('#confirm-remove').onclick=()=>{mutate(()=>{if(type==='section'){doc.sections=doc.sections.filter(s=>s.id!==sectionId);sectionId='identity'}else{const s=currentSection();s.items=s.items.filter(i=>i.id!==itemId);itemId=s.items[0]?.id}});$('#dialog').close()}}
function moveSection(sid,dir){mutate(()=>{let n=doc.sections.findIndex(s=>s.id===sid),dest=n+dir;if(dest<0||dest>=doc.sections.length)return;[doc.sections[n],doc.sections[dest]]=[doc.sections[dest],doc.sections[n]]})}
async function versions(){await persist();modal('简历版本','<p>正在读取本机保存的简历…</p>');try{const list=await(await fetch('/api/resumes')).json();$('#dialog-body').innerHTML='<button id="duplicate" class="primary">复制为新版本</button><p class="hint">每个版本独立保存内容和排版。浏览器刷新后仍可打开。</p>'+list.map(v=>`<div class="historyrow"><div><strong>${esc(v.name)}</strong><small>${new Date(v.updatedAt||v.createdAt).toLocaleString('zh-CN')}</small></div>${v.id===doc.id?'<span class="tag">当前版本</span>':`<button data-open-doc="${v.id}">打开</button>`}</div>`).join('')+'<h3>当前版本的恢复记录</h3><div id="snapshots">正在读取…</div>';const hist=await(await fetch('/api/resumes/'+doc.id+'/history')).json();$('#snapshots').innerHTML=hist.map((v,i)=>`<div class="historyrow"><div><strong>${esc(v.name)}</strong><small>${new Date(v.updatedAt||v.createdAt).toLocaleString('zh-CN')}</small></div><button data-restore="${i}">恢复</button></div>`).join('')||'<p class="hint">保存后会保留最近 30 次记录。</p>';$$('[data-restore]').forEach(b=>b.onclick=()=>{mutate(()=>{const oldId=doc.id;doc=clone(hist[+b.dataset.restore]);doc.id=oldId},false);renderAll();$('#dialog').close();notify('已恢复，可撤销')})}catch{$('#dialog-body').textContent='读取失败，请确认本地服务仍在运行。'}}
function plainText(){return [doc.identity.name,doc.identity.role,doc.identity.contact,...doc.sections.filter(s=>s.visible).flatMap(s=>[s.title,...s.items.flatMap(i=>[i.title,i.meta,i.dates,i.body.ops.map(o=>typeof o.insert==='string'?o.insert:'').join('')])])].filter(Boolean).join('\n\n')}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;($('#dialog').open?$('#dialog-body'):document.body).append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
function colorRGB(css){const m=css.match(/[\d.]+/g);return m?m.slice(0,3).map(Number):[36,48,59]}
function pageData(){renderPages();return $$('.sheet').map(sheet=>{const base=sheet.getBoundingClientRect(),scale=base.width/794;const texts=[],lines=[],images=[];const walker=document.createTreeWalker(sheet,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const t=walker.currentNode;if(!t.textContent.trim())continue;const cs=getComputedStyle(t.parentElement);let run=null;for(let n=0;n<t.length;n++){const range=document.createRange();range.setStart(t,n);range.setEnd(t,n+1);const r=range.getBoundingClientRect();if(!r.width&&!r.height)continue;const x=(r.x-base.x)/scale,y=(r.y-base.y)/scale;const character=t.textContent[n];if(run&&Math.abs(run.y-y)<.5&&Math.abs(run.end-x)<1.5){run.text+=character;run.end=x+r.width/scale}else{run={text:character,x,y,end:x+r.width/scale,height:r.height/scale,size:parseFloat(cs.fontSize),font:cs.fontFamily.includes('ResumeSerif')?'serif':'sans',bold:+cs.fontWeight>=600,italic:cs.fontStyle==='italic',underline:cs.textDecorationLine.includes('underline'),strike:cs.textDecorationLine.includes('line-through'),color:colorRGB(cs.color)};texts.push(run)}}}
for(const e of sheet.querySelectorAll('.sectionheading')){const r=e.getBoundingClientRect(),cs=getComputedStyle(e);if(parseFloat(cs.borderBottomWidth))lines.push({x:(r.left-base.left)/scale,y:(r.bottom-base.top)/scale,width:r.width/scale,height:parseFloat(cs.borderBottomWidth),color:colorRGB(cs.borderBottomColor)});if(parseFloat(cs.borderLeftWidth))lines.push({x:(r.left-base.left)/scale,y:(r.top-base.top)/scale,width:parseFloat(cs.borderLeftWidth),height:r.height/scale,color:colorRGB(cs.borderLeftColor)})}for(const e of sheet.querySelectorAll('img')){const r=e.getBoundingClientRect();images.push({src:e.src,x:(r.left-base.left)/scale,y:(r.top-base.top)/scale,width:r.width/scale,height:r.height/scale})}
const columns=[...sheet.querySelectorAll('.column')].map(c=>[...c.children].map(e=>({className:e.className,html:e.innerHTML})));const links=[...sheet.querySelectorAll('a[href]')].flatMap(a=>[...a.getClientRects()].map(r=>({href:a.href,x:(r.left-base.left)/scale,y:(r.top-base.top)/scale,width:r.width/scale,height:r.height/scale})));return {texts,lines,images,columns,links};})}
async function exportFile(kind){if(kind==='txt'){download(new Blob([plainText()],{type:'text/plain;charset=utf-8'}),doc.name+'.txt');return}if(kind==='json'){download(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),doc.name+'.career.json');return}notify('正在生成 '+kind.toUpperCase()+'…');const buttons=$$('[data-export]');buttons.forEach(b=>b.disabled=true);try{await document.fonts.ready;const payload={document:doc,pages:pageData()};const res=await fetch('/api/export/'+kind,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw Error(await res.text());const result=await res.json();let link=$('#generated-download');if(!link){link=document.createElement('a');link.id='generated-download';link.style.cssText='display:block;margin-top:18px;padding:14px;background:#edf3ff;border-radius:9px;color:#3267ee;text-decoration:none';$('#dialog-body').append(link)}link.href=result.url;link.download=doc.name+'.'+kind;link.textContent='↓ 下载已生成的 '+kind.toUpperCase()+'（'+Math.ceil(result.bytes/1024)+' KB）';notify(kind.toUpperCase()+' 已生成，点击下载链接即可保存')}catch(e){notify('导出失败：'+e.message.slice(0,130))}finally{buttons.forEach(b=>b.disabled=false)}}
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.tab)tab(b.dataset.tab);if(b.dataset.select)choose(b.dataset.select);if(b.dataset.item){itemId=b.dataset.item;renderPanel()}if(b.dataset.move){const[s,n]=b.dataset.move.split(':');moveSection(s,+n)}if(b.dataset.template){mutate(()=>doc.style.template=b.dataset.template,false);renderStyle()}if(b.dataset.export)await exportFile(b.dataset.export);if(b.dataset.openDoc){if(!await persist()){notify('当前简历未保存，暂不切换版本');return}doc=await(await fetch('/api/resumes/'+b.dataset.openDoc)).json();undo=[];redo=[];sectionId='identity';localStorage.setItem(KEY,JSON.stringify(doc));renderAll();$('#dialog').close();setStatus('已打开本机版本')}
switch(b.id){case'undo':applyHistory(undo,redo);break;case'redo':applyHistory(redo,undo);break;case'add-section':modal('添加模块','<label>模块名称<input id="new-section-name" value="自定义模块"></label><button id="create-section" class="primary wide">添加并编辑</button>');break;case'create-section':{const name=$('#new-section-name').value.trim();if(!name)return;mutate(()=>{const s={id:id(),title:name,visible:true,items:[item('','','','')]};doc.sections.push(s);sectionId=s.id;itemId=s.items[0].id});$('#dialog').close();tab('content');break}case'add-item':mutate(()=>{const i=item('','','','');currentSection().items.push(i);itemId=i.id});break;case'delete-item':confirmRemove('item');break;case'delete-section':confirmRemove('section');break;case'item-up':case'item-down':mutate(()=>{const a=currentSection().items,n=a.findIndex(i=>i.id===itemId),p=n+(b.id==='item-up'?-1:1);if(p>=0&&p<a.length)[a[n],a[p]]=[a[p],a[n]]});break;case'fit-page':mutate(()=>{doc.style.size=Math.max(10,doc.style.size-0.5);doc.style.margin=14;doc.style.gap=9;doc.style.leading=1.3},false);renderStyle();notify('已调整为紧凑排版，文字保持完整，可撤销');break;case'zoom-in':autofit=false;zoom=Math.min(1.6,zoom+.1);applyZoom();break;case'zoom-out':autofit=false;zoom=Math.max(.3,zoom-.1);applyZoom();break;case'zoom-fit':autofit=true;applyZoom();break;case'preview':$('#app').classList.toggle('preview-mode');b.textContent=$('#app').classList.contains('preview-mode')?'返回编辑':'预览';applyZoom();break;case'versions':versions();break;case'duplicate':{await persist();checkpoint();doc=clone(doc);doc.id=id();doc.name+=' · 副本';doc.createdAt=new Date().toISOString();changed();renderAll();$('#dialog').close();notify('已创建独立副本');break}case'export':modal('导出简历',`<div class="export-grid"><button data-export="pdf"><strong>PDF 文档</strong><small>保留纸张排版 · 文字可选择</small></button><button data-export="docx"><strong>Word 文档</strong><small>可编辑文字与格式 · 适用 Word / WPS</small></button><button data-export="png"><strong>PNG 图片</strong><small>清晰长图 · 多页纵向拼接</small></button><button data-export="txt"><strong>纯文本</strong><small>便于复制到网申表单</small></button></div><p class="hint">DOCX 的分页可能随 Word / WPS 字体环境变化。PDF 按当前纸张布局生成。</p><button data-export="json">备份可编辑源文件</button>`);break;case'close-dialog':$('#dialog').close();break;case'remove-photo':mutate(()=>doc.identity.photo='');break;}});
$('#pages').addEventListener('click',e=>{const a=e.target.closest('.atom');if(a){if($('#app').classList.contains('preview-mode'))return;choose(a.dataset.section,a.dataset.item)}});
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.identity)typed(()=>doc.identity[el.dataset.identity]=el.value);if(el.id==='doc-name')typed(()=>doc.name=el.value);if(el.id==='section-title'){typed(()=>currentSection().title=el.value);renderOutline()}for(const k of ['title','meta','dates'])if(el.id==='item-'+k)typed(()=>currentItem()[k]=el.value);if(['font','size','leading','margin','gap','color'].includes(el.id)){typed(()=>doc.style[el.id]=['font','color'].includes(el.id)?el.value:+el.value);if($('#'+el.id+'-value'))$('#'+el.id+'-value').textContent=el.value+({size:' pt',leading:' 倍',margin:' mm',gap:' px'}[el.id])}});
document.addEventListener('change',async e=>{const el=e.target;if(el.dataset.visible)mutate(()=>doc.sections.find(s=>s.id===el.dataset.visible).visible=el.checked);if(el.id==='break-before')mutate(()=>currentSection().breakBefore=el.checked,false);if(el.id==='photo-upload'){const f=el.files[0];if(!f)return;if(f.size>3*1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type)){notify('请选择 3 MB 以内的 PNG / JPG / WebP 照片');return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=174;canvas.height=228;const ctx=canvas.getContext('2d'),ratio=Math.max(174/img.width,228/img.height),w=img.width*ratio,h=img.height*ratio;ctx.drawImage(img,(174-w)/2,(228-h)/2,w,h);mutate(()=>doc.identity.photo=canvas.toDataURL('image/jpeg',.9))};img.src=reader.result};reader.readAsDataURL(f)}});
$('#outline').addEventListener('dragstart',e=>{const r=e.target.closest('[data-drag]');if(r){dragId=r.dataset.drag;r.classList.add('dragging');e.dataTransfer.setData('text/plain',dragId)}});$('#outline').addEventListener('dragover',e=>e.preventDefault());$('#outline').addEventListener('dragend',()=>$$('.dragging').forEach(e=>e.classList.remove('dragging')));$('#outline').addEventListener('drop',e=>{e.preventDefault();const t=e.target.closest('[data-drag]')?.dataset.drag;if(!dragId||!t||dragId===t)return;mutate(()=>{const i=doc.sections.findIndex(s=>s.id===dragId),j=doc.sections.findIndex(s=>s.id===t);doc.sections.splice(j,0,doc.sections.splice(i,1)[0])});dragId=null});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();persist()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopPropagation();applyHistory(e.shiftKey?redo:undo,e.shiftKey?undo:redo)}},true);window.addEventListener('beforeunload',e=>{if(dirty){persist();e.preventDefault();e.returnValue=''}});new ResizeObserver(()=>applyZoom()).observe($('#paper-scroll'));
async function init(){try{let seed;try{seed=JSON.parse(sessionStorage.getItem('career-resume-seed')||'null')}catch{}if(seed){sessionStorage.removeItem('career-resume-seed');doc=fromProfile(seed)}else{let local;try{local=JSON.parse(localStorage.getItem(KEY)||'null')}catch{}if(local?.schema===1)doc=local;else{const list=await(await fetch('/api/resumes')).json();if(list.length)doc=await(await fetch('/api/resumes/'+list[0].id)).json();else doc=fromProfile(null)}}renderAll();await document.fonts.ready;renderPages();await persist()}catch(e){setStatus('打开失败，请刷新或重启本地服务',true);notify(e.message)}}
init();
})();
